// Generated by scripts/generate-operator-schemas.mjs. Edit the source tool file.

import { z } from "zod";

import type { Tool } from "./index.js";

const targetSchema = z.object({
  ref: z.string().min(1).max(512),
  format: z.string().min(1).max(32).optional(),
});

const inputSchema = z.object({
  session_id: z.string().uuid(),
  merchant: z.string().trim().min(1).max(256),
  amount_cents: z.number().int().min(0).max(2_147_483_647),
  currency: z.string().regex(/^[A-Za-z]{3}$/),
  item: z.string().trim().min(1).max(500),
  reason: z.string().trim().min(1).max(500),
  card_ref: z.string().trim().min(1).max(64),
  approval_id: z.string().trim().min(1).max(128).optional(),
  fields: z
    .object({
      pan: targetSchema.optional(),
      cvv: targetSchema.optional(),
    })
    // Expiry and cardholder name are NOT inject targets: reject them loudly
    // instead of silently stripping, so the agent reroutes to operate_type.
    .strict(),
});

export const injectCardTool: Tool = {
  name: "inject_card",
  description:
    "Release one saved card under the existing single human purchase approval and fill only the supplied observation refs. Supply session_id and refs for pan/cvv from operate_observe; each may target the main document or any reachable frame. Expiry, cardholder name, and billing are NOT inject targets and are not secret: after approval the result carries exp_month, exp_year, name, and any stored billing alongside last4, and you type those with operate_type/operate_select like any other field. After approval the session also exposes the card as opaque per-digit masked tokens you can place into ANY field ref yourself with operate_type: {{pan}} and {{cvv}} type the whole value, {{pan:N}} and {{cvv:N}} type one digit (1-based, N up to the returned pan_length/cvv_length); the broker substitutes the real digit at the keystroke boundary and the digits are never shown to you or masked out of every observation, screenshot, and error. Use the refs for the ordinary path and the tokens for arbitrary layouts, single-digit boxes, remounts, re-validation, or post-error re-arm. Avoid provider helper/autofill/focus inputs and choose the actual card control. This tool never searches for payment providers, chooses a card UI, reads or validates the total, clicks submit, clears fields, or diagnoses the checkout. Partial results are ordinary browser outcomes; retry changed refs with the same approval_id. Before placing the order, re-observe and confirm no competing saved-card control is selected. The operator detects a rendered 3-D Secure challenge on observation or action results and notifies the cardholder once; do not solve or wait on the challenge yourself — keep observing until the checkout resolves. The released PAN/CVV are masked from all normal operator output before the first write.",
  inputSchema,
  jsonInputSchema: {
    type: "object",
    required: [
      "session_id",
      "merchant",
      "amount_cents",
      "currency",
      "item",
      "reason",
      "card_ref",
      "fields",
    ],
    properties: {
      session_id: { type: "string", format: "uuid" },
      merchant: { type: "string" },
      amount_cents: { type: "integer", minimum: 0 },
      currency: { type: "string", pattern: "^[A-Za-z]{3}$" },
      item: { type: "string" },
      reason: { type: "string" },
      card_ref: { type: "string" },
      approval_id: { type: "string" },
      fields: {
        type: "object",
        properties: Object.fromEntries(
          ["pan", "cvv"].map((field) => [
            field,
            {
              type: "object",
              required: ["ref"],
              properties: {
                ref: { type: "string" },
                format: { type: "string" },
              },
            },
          ]),
        ),
      },
    },
  },
  annotations: {
    readOnlyHint: false,
    destructiveHint: false,
    idempotentHint: true,
  },
  async handler(args, api, context) {
    return await (
      await import("./inject-card.js")
    ).injectCardTool.handler(args as never, api, context);
  },
};
