// Generated by scripts/generate-operator-schemas.mjs. Edit the source tool file.

import { z } from "zod";

import type { Tool } from "./index.js";

import { captureSourceSchema } from "../bot/credential-capture.js";

const proxySchema = z
  .string()
  .min(1)
  .max(2048)
  .superRefine((value, ctx) => {
    let parsed: URL;
    try {
      parsed = new URL(value);
    } catch {
      ctx.addIssue({
        code: z.ZodIssueCode.custom,
        message: "proxy must be a valid HTTP, HTTPS, or SOCKS5 URL",
      });
      return;
    }
    if (parsed.hostname.length === 0 || !["http:", "https:", "socks5:"].includes(parsed.protocol)) {
      ctx.addIssue({
        code: z.ZodIssueCode.custom,
        message: "proxy must be a valid HTTP, HTTPS, or SOCKS5 URL",
      });
      return;
    }
    if (
      parsed.protocol === "socks5:" &&
      (parsed.username.length > 0 || parsed.password.length > 0)
    ) {
      ctx.addIssue({
        code: z.ZodIssueCode.custom,
        message:
          "Authenticated SOCKS5 is unsupported by the browser engine; use HTTP/HTTPS with credentials or unauthenticated SOCKS5",
      });
      return;
    }
    if (
      (parsed.protocol === "http:" || parsed.protocol === "https:") &&
      parsed.password.length > 0 &&
      parsed.username.length === 0
    ) {
      ctx.addIssue({
        code: z.ZodIssueCode.custom,
        message:
          "Password-only HTTP/HTTPS proxy credentials are unsupported; include a non-empty username or use an unauthenticated proxy",
      });
      return;
    }
    try {
      decodeURIComponent(parsed.username);
      decodeURIComponent(parsed.password);
    } catch {
      ctx.addIssue({
        code: z.ZodIssueCode.custom,
        message: "proxy credentials contain invalid percent encoding",
      });
    }
  });

const startSchema = z.object({
  service_url: z.string().url(),
  format: z.enum(["compact", "full"]).optional(),
  // Sensitive: may include proxy credentials. It is launch-only and is never
  // retained in the session state, action trail, or status.
  proxy: proxySchema.optional(),
  // Operate tasks that act AS the user (drive a gated app on an existing
  // account) set this so start fails closed to a connect hand-back if no live
  // Google session exists — rather than driving into a mid-task login wall.
});

const DOM_OBSERVATION_CONTRACT =
  'With `format:"full"`, `browser-use-dom` returns a tab-indented `dom` tree with text and `[@e:...]` controls. ' +
  "`|SHADOW(open)|` / `|SHADOW(closed)|` mark shadow hosts; `not-targetable=true` refs are display-only. " +
  "`*` marks a new control; `more_above` / `more_below` signal offscreen content. " +
  "On `delta:true`, a present `dom` replaces the prior tree; otherwise keep it and remove refs in `removed`. " +
  "Without delta, reset the view. Refs stay usable on the same document; on stale_ref, observe again. ";

const CONTROL_QUERY_CONTRACT =
  'The default `format:"compact"` response is `browser-use-control-query`: `safe_table` pages controls, including offscreen ones, as `[ref,role,facts?]`. ' +
  "Arbitrary page text is absent from this control map; use full format when text matters. " +
  "Roles b/l/t/s/c/r/tb/m/f mean button/link/textbox/select/checkbox/radio/tab/menuitem/file; other roles are literal. " +
  "`facts` joins an `@label` alias with hints: s=c/u/d/r means checked/unchecked/disabled/required, v=offscreen, a=action, f=field, q=choice-position/total, and x=s/x for same/cross-origin frame (absent x means main frame). `nf=1` is a non-fillable listener; use its separately listed field. " +
  "Query or role filters controls; `m=n/r/t/c` marks name/role/text/context matches. " +
  "`semantic.blocked` and `semantic.blockers` report challenges, validation, dialogs, and error pages regardless of stage. Dialog options include actionable exits; an absent exit ref has target=unavailable. " +
  "Use `overflow.next_cursor` to page with the same query and role; `hint_overflow.next_cursor` pages hints. Document changes invalidate cursors. ";

const ACTION_FORMAT_NOTE =
  'Returns a compact control map; `delta:true` lists changed rows in `safe_table` and departed refs in `removed`. `w=acted` marks the acted row. Use `format:"full"` for the DOM tree. ';

const ACTION_FORMATS = ["compact", "full"] as const;

const actionFormatSchema = z.enum(ACTION_FORMATS);

const actionFormatJson = { type: "string", enum: [...ACTION_FORMATS] };

const observeSchema = z.object({
  session_id: z.string().min(1),
  query: z.string().max(160).optional(),
  cursor: z.string().max(1024).optional(),
  role: z
    .string()
    .min(1)
    .max(64)
    .regex(/^[a-z][a-z0-9-]*$/)
    .describe("Emitted control role, including literal roles such as slider or generic")
    .optional(),
  format: z.enum(["compact", "full"]).optional(),
  subtree_ref: z.string().min(1).max(512).optional(),
  raw_attributes: z.boolean().optional(),
});

const screenshotSchema = z.object({
  session_id: z.string().min(1),
  // Index into the SAME frame ordering operate_observe's frame_origin
  // implies (page.frames() order) — capture one frame in isolation instead
  // of the whole page. Mutually exclusive with frame_url_contains; pass at
  // most one.
  frame_index: z.number().int().min(0).optional(),
  // A substring of a frame's URL (e.g. "cardinalcommerce.com") — capture
  // whichever frame matches instead of the whole page.
  frame_url_contains: z.string().min(1).max(300).optional(),
  // Default false (viewport only, matches what a human actually sees).
  // Ignored when a frame is targeted (a frame capture is always that
  // frame's own full box).
  full_page: z.boolean().optional(),
});

const networkSchema = z.object({
  session_id: z.string().min(1),
  since: z.number().int().min(0).optional(),
  request_id: z.string().min(1).max(256).optional(),
});

const storeShape = z.object({
  service: z.string().min(1).max(120),
  label: z.string().min(1).max(60).optional(),
  env_var_suggestion: z.string().min(1).max(120).optional(),
  type: z.string().min(1).max(60).optional(),
  // Explicit API hosts: where this key may LATER be sent by the proxy.
  // Read them off the API base URL the page/SDK snippet shows — a grounded
  // read, not a guess. Unioned with the service-default + start/auto_widen
  // scope (never mid_session task scope). Omit for a single-service key.
  api_hosts: z.array(z.string().min(1).max(253)).max(10).optional(),
  egress_hosts: z.array(z.string().min(1).max(253)).max(10).optional(),
  auth_shape: z
    .string()
    .max(120)
    .regex(/^(bearer|header:.+|query:.+)$/, "auth_shape must be bearer|header:<name>|query:<param>")
    .optional(),
});

const captureSchema = z
  .object({
    store: storeShape,
    source: captureSourceSchema,
    write_id: z
      .string()
      .min(1)
      .max(128)
      .regex(/^[a-zA-Z0-9:_-]+$/)
      .optional(),
  })
  .strict();

const captureClickSchema = captureSchema.omit({ write_id: true });

const captureExtractSchema = captureSchema.extend({
  source: captureSourceSchema.refine(
    (source) => !("clipboard" in source),
    "capture.source.clipboard is only valid on operate_click",
  ),
});

const captureJson = {
  type: "object",
  additionalProperties: false,
  required: ["store", "source"],
  properties: {
    store: {
      type: "object",
      required: ["service"],
      properties: {
        service: { type: "string" },
        label: { type: "string" },
        env_var_suggestion: { type: "string" },
        type: { type: "string" },
        api_hosts: { type: "array", items: { type: "string" } },
        egress_hosts: {
          type: "array",
          items: { type: "string" },
          deprecated: true,
          description: "Deprecated alias for api_hosts; removed next minor",
        },
        auth_shape: { type: "string" },
      },
    },
    source: {
      type: "object",
      additionalProperties: false,
      oneOf: [
        { required: ["role"], not: { required: ["selector"] } },
        {
          required: ["selector"],
          not: { anyOf: [{ required: ["role"] }, { required: ["name"] }] },
        },
        {
          required: ["clipboard"],
          not: {
            anyOf: [
              { required: ["role"] },
              { required: ["name"] },
              { required: ["selector"] },
              { required: ["container"] },
            ],
          },
        },
      ],
      properties: {
        clipboard: { type: "boolean", const: true },
        selector: { type: "string", minLength: 1, maxLength: 2000 },
        role: { type: "string", enum: ["textbox", "code"] },
        name: { type: "string", maxLength: 200 },
        container: {
          type: "object",
          additionalProperties: false,
          required: ["role"],
          properties: {
            role: { type: "string", enum: ["dialog", "region"] },
            name: { type: "string", maxLength: 200 },
          },
        },
      },
    },
    write_id: { type: "string", minLength: 1, maxLength: 128, pattern: "^[a-zA-Z0-9:_-]+$" },
  },
};

const captureJsonFor = (toolName: string) => {
  const { write_id: _writeId, ...actionProperties } = captureJson.properties;
  if (toolName === "operate_click") return { ...captureJson, properties: actionProperties };
  const { clipboard: _clipboard, ...sourceProperties } = captureJson.properties.source.properties;
  return {
    ...captureJson,
    properties: {
      ...(toolName === "operate_extract" ? captureJson.properties : actionProperties),
      source: {
        ...captureJson.properties.source,
        oneOf: captureJson.properties.source.oneOf.slice(0, 2),
        properties: sourceProperties,
      },
    },
  };
};

const CAPTURE_NOTE =
  " Optional capture:{store,source:{role,name?,container?}|{selector,container?}} stores one revealed value after the action and returns metadata, not the value; resolved_source names the element. " +
  "Use store.api_hosts for API hosts this credential may be sent to; store.egress_hosts is a deprecated alias removed next minor. " +
  "Role and value-free CSS selector sources can cross open shadow roots; a unique secret-shaped textbox can match without an id. " +
  "capture_unresolved returns candidate_count 0 and found roles/names; capture_ambiguous means several matches. " +
  "An unresolved capture does not block unrelated actions. Never paste a secret into a page field to read it.";

const CLICK_CAPTURE_NOTE =
  " On operate_click, source:{clipboard:true} stores only a new clipboard value written by that click; " +
  "an unchanged or empty clipboard stores nothing and reports capture_clipboard_unchanged or capture_clipboard_empty.";

const EXTRACT_CAPTURE_NOTE =
  " Only operate_extract accepts capture.write_id to retry storage after an unresolved capture.";

const storeJsonProps = {
  service: { type: "string" },
  label: { type: "string" },
  env_var_suggestion: { type: "string" },
  type: { type: "string" },
  api_hosts: { type: "array", items: { type: "string" } },
  egress_hosts: {
    type: "array",
    items: { type: "string" },
    deprecated: true,
    description: "Deprecated alias for api_hosts; removed next minor",
  },
  auth_shape: { type: "string" },
} as const;

const formSelectionsSchema = z
  .record(z.string().min(1).max(200), z.string().min(1).max(4096))
  .refine((value) => Object.keys(value).length > 0, "Provide at least one selection")
  .refine((value) => Object.keys(value).length <= 12, "At most 12 selections per call")
  .describe("Map each current control ref or @label to its visible option text.");

const extractSchema = z.object({
  capture: captureExtractSchema.optional(),
  session_id: z.string().min(1),
  into_slot: z.string().min(1).max(60).optional(),
  store: storeShape.optional(),
});

const finishDataSchema = z.record(z.union([z.string().max(4000), z.number(), z.boolean()]));

const prepareLoginSchema = z.object({
  session_id: z.string().min(1),
  login_slot: z.string().min(1).max(60).optional(),
  password_slot: z.string().min(1).max(60).optional(),
  password_length: z.number().int().min(16).max(64).optional(),
});

const storeLoginSchema = z.object({
  session_id: z.string().min(1),
  service: z.string().min(1).max(120),
  login_slot: z.string().min(1).max(60).optional(),
  password_slot: z.string().min(1).max(60).optional(),
  label: z.string().min(1).max(120).optional(),
  signin_url: z.string().url().optional(),
  login_hosts: z.array(z.string().min(1).max(253)).min(1).max(20),
});

const vaultCredentialFieldsDescription =
  'Exact field_names from list_credentials for the selected reference. Defaults to ["login","password"] ' +
  'for logins saved by operate_login; use ["username","password"] when those are the stored names. ' +
  "Use operate_type with each returned slot to fill its matching form control.";

const vaultCredentialFieldsJson = {
  type: "array",
  items: { type: "string" },
  minItems: 1,
  maxItems: 20,
  default: ["login", "password"],
  description: vaultCredentialFieldsDescription,
};

const sealVaultCredentialBaseSchema = z.object({
  session_id: z.string().min(1),
  reference: z.string().min(1).max(400).optional(),
  service: z.string().min(1).max(120).optional(),
  fields: z
    .array(z.string().min(1).max(120))
    .min(1)
    .max(20)
    .default(["login", "password"])
    .describe(vaultCredentialFieldsDescription),
  slot_prefix: z.string().min(1).max(60).default("vault"),
});

const loginPrepareSignupSchema = prepareLoginSchema.extend({
  action: z.literal("prepare_signup"),
});

const loginStoreSignupSchema = storeLoginSchema.extend({
  action: z.literal("store_signup"),
});

const loginLoadSavedSchema = sealVaultCredentialBaseSchema
  .extend({ action: z.literal("load_saved") })
  .refine((b) => b.reference !== undefined || b.service !== undefined, {
    message: "one of reference or service is required",
  });

const loginOAuthSchema = z.object({
  session_id: z.string().min(1),
  action: z.literal("oauth").optional(),
  provider: z.enum(["google", "github"]),
  ref: z.string().min(1).max(200),
});

const loginSchema = z.union([
  loginOAuthSchema,
  loginPrepareSignupSchema,
  loginStoreSignupSchema,
  loginLoadSavedSchema,
]);

const sessionShape = { session_id: z.string().min(1) };

const refSchema = z.string().min(1).max(200);

const sessionJson = { session_id: { type: "string" } };

const refJson = { ref: { type: "string" } };

const navigateSchema = z.object({ ...sessionShape, url: z.string().url() });

const screenshotPointSchema = z
  .object({
    screenshot_id: z.string().uuid(),
    x: z.number().finite().min(0),
    y: z.number().finite().min(0),
  })
  .strict();

const clickSchema = z
  .object({
    ...sessionShape,
    ref: refSchema.optional(),
    screenshot: screenshotPointSchema.optional(),
    capture: captureClickSchema.optional(),
    format: actionFormatSchema.optional(),
  })
  .refine((args) => (args.ref !== undefined) !== (args.screenshot !== undefined), {
    message: "Provide exactly one of ref or screenshot",
  });

const typeSchema = z
  .object({
    ...sessionShape,
    ref: refSchema,
    text: z.string().max(4096).optional(),
    slot: z.string().min(1).max(60).optional(),
    submit: z.boolean().optional(),
    capture: z.unknown().optional(),
    format: actionFormatSchema.optional(),
  })
  .refine((args) => (args.text !== undefined) !== (args.slot !== undefined), {
    message: "Provide exactly one of text or slot",
  });

const selectSchema = z
  .object({
    ...sessionShape,
    ref: refSchema.optional(),
    values: z.array(z.string().min(1).max(4096)).length(1).optional(),
    selections: formSelectionsSchema.optional(),
    capture: z.unknown().optional(),
    country: z.string().min(1).max(60).optional(),
    format: actionFormatSchema.optional(),
  })
  .superRefine((args, ctx) => {
    const modes =
      Number(args.ref !== undefined || args.values !== undefined) +
      Number(args.selections !== undefined) +
      Number(args.country !== undefined);
    if (modes !== 1 || (args.ref !== undefined) !== (args.values !== undefined)) {
      ctx.addIssue({
        code: z.ZodIssueCode.custom,
        message: "Provide ref + values, selections, or country",
      });
    }
  });

const uploadSchema = z.object({
  ...sessionShape,
  target: refSchema,
  path: z.string().startsWith("/"),
  format: actionFormatSchema.optional(),
});

const pressSchema = z.object({
  ...sessionShape,
  key: z.string().min(1).max(40),
  capture: z.unknown().optional(),
  format: actionFormatSchema.optional(),
});

const scrollSchema = z.object({
  ...sessionShape,
  direction: z.enum(["down", "up", "bottom", "top"]).default("down"),
  format: actionFormatSchema.optional(),
});

const waitSchema = z.object({
  ...sessionShape,
  milliseconds: z.number().int().min(0).max(30_000).default(1_000),
  format: actionFormatSchema.optional(),
});

const readInboxSchema = z.object({
  session_id: z.string().min(1),
  sender: z.string().min(1).max(200).optional(),
  recipient: z.string().min(3).max(320).optional(),
  into_slot: z.string().min(1).max(120).optional(),
  grant_inbox_consent: z.boolean().optional(),
});

const publicFinishSchema = z
  .object({
    ...sessionShape,
    outcome: z.enum(["none", "credentials", "result"]).default("none"),
    store: z.unknown().optional(),
    summary: z.string().max(4000).optional(),
    data: finishDataSchema.optional(),
  })
  .superRefine((args, ctx) => {
    if (args.outcome === "result" && args.summary === undefined && args.data === undefined)
      ctx.addIssue({
        code: z.ZodIssueCode.custom,
        message: "result outcome requires summary or data",
      });
  });

const driveSchema = z
  .object({
    session_id: z.string().min(1).optional(),
    url: z.string().url().optional(),
    goal: z.string().min(1).max(4000),
    facts: z.record(z.string(), z.string()).optional(),
    max_steps: z.number().int().min(1).max(60).optional(),
    max_seconds: z.number().int().min(1).max(120).optional(),
    answer: z.string().min(1).max(200).optional(),
  })
  .superRefine((value, ctx) => {
    const hasSession = value.session_id !== undefined;
    const hasUrl = value.url !== undefined;
    if (hasSession === hasUrl) {
      ctx.addIssue({
        code: z.ZodIssueCode.custom,
        message: "Provide exactly one of session_id or url",
      });
    }
  });

export const provisionStartTool: Tool = {
  name: "operate_start",
  description:
    "Begin an interactive website task: opens a browser on the " +
    "user's machine at service_url and returns the initial page observation. " +
    CONTROL_QUERY_CONTRACT +
    'Use `format:"full"` only when the page DOM and text are needed. A released card\'s PAN (complete ordinary spellings and prefixes of at least eight digits) and security code are masked; all other emitted content stays verbatim. ' +
    DOM_OBSERVATION_CONTRACT +
    "Use operate_start when you want to inspect the first page before choosing steps. For a known multi-step goal, call operate_drive with url, goal, and facts directly. " +
    "operate_click, operate_type, operate_select, operate_upload, operate_navigate, operate_scroll, and operate_login " +
    "complete individual steps. Resume a drive handoff on the same session with answer or added facts. " +
    "inject_card releases a saved card into pan/cvv refs and exposes masked {{pan}}/{{cvv}} per-digit tokens for operate_type placement. " +
    "Call operate_extract when you reach the credentials. Always operate_finish when done. The " +
    "browser has unrestricted egress.",
  inputSchema: startSchema,
  jsonInputSchema: {
    type: "object",
    required: ["service_url"],
    properties: {
      service_url: { type: "string" },
      format: { type: "string", enum: ["compact", "full"] },
      proxy: {
        type: "string",
        description:
          "Optional per-session HTTP/HTTPS proxy URL with or without credentials, or unauthenticated SOCKS5 URL. HTTP/HTTPS passwords require a non-empty username; authenticated SOCKS5 is unsupported by the browser engine. Sensitive and launch-only; never returned or saved.",
      },
    },
  },
  async handler(args, api, context) {
    return await (
      await import("./provision-drive.js")
    ).provisionStartTool.handler(args as never, api, context);
  },
};

export const provisionObserveTool: Tool = {
  name: "operate_observe",
  description:
    "Re-read the current page of an operate session. " +
    CONTROL_QUERY_CONTRACT +
    'Use `format:"full"` only when the page DOM and text are needed. A released card\'s PAN (complete ordinary spellings and prefixes of at least eight digits) and security code are masked; all other emitted content stays verbatim. ' +
    DOM_OBSERVATION_CONTRACT +
    "Supplying query, role, or cursor always selects the compact control-map path, regardless of format.",
  inputSchema: observeSchema,
  jsonInputSchema: {
    type: "object",
    required: ["session_id"],
    properties: {
      session_id: { type: "string" },
      query: { type: "string" },
      cursor: { type: "string" },
      role: {
        type: "string",
        minLength: 1,
        maxLength: 64,
        pattern: "^[a-z][a-z0-9-]*$",
      },
      format: { type: "string", enum: ["compact", "full"] },
      subtree_ref: { type: "string" },
      raw_attributes: { type: "boolean" },
    },
  },
  async handler(args, api, context) {
    return await (
      await import("./provision-drive.js")
    ).provisionObserveTool.handler(args as never, api, context);
  },
};

export const provisionScreenshotTool: Tool = {
  name: "operate_screenshot",
  description:
    "Capture rendered pixels from the viewport (or full_page:true) or one frame via frame_index or frame_url_contains. " +
    "A screenshot costs more context than operate_observe; use it when visual state or a coordinate click matters, " +
    "including a captcha or 3-D Secure ACS frame. During bank approval, short, non-blocking screenshots or observations " +
    "can watch for a change. This read does not interact with the page. Released PAN and security code in injected " +
    "controls and identified displayed copies are covered; if masking fails, capture fails. " +
    "A click_binding authorizes one dispatched operate_click point in original image pixels for 60 seconds; " +
    "navigation, scroll, viewport, or frame changes invalidate it. Without a binding, capture again before a coordinate click.",
  inputSchema: screenshotSchema,
  jsonInputSchema: {
    type: "object",
    required: ["session_id"],
    properties: {
      session_id: { type: "string" },
      frame_index: { type: "number" },
      frame_url_contains: { type: "string" },
      full_page: { type: "boolean" },
    },
  },
  jsonOutputSchema: {
    type: "object",
    properties: {
      click_binding: {
        type: "object",
        required: ["screenshot_id", "width", "height", "coordinate_space"],
        properties: {
          screenshot_id: { type: "string", format: "uuid" },
          width: { type: "integer", minimum: 1 },
          height: { type: "integer", minimum: 1 },
          coordinate_space: { const: "image_pixels" },
        },
      },
    },
    additionalProperties: true,
  },
  async handler(args, api, context) {
    return await (
      await import("./provision-drive.js")
    ).provisionScreenshotTool.handler(args as never, api, context);
  },
};

export const provisionNetworkTool: Tool = {
  name: "operate_network",
  description:
    "Read raw browser evidence collected since session start: requests, responses, pending/completed/failed state, HTTP status, loading failures, CORS/blocked reasons, console messages, exceptions, and screenshot events. Pass the returned cursor as since for an incremental read, or request_id for one request. This surface does not diagnose payment stages. Released card PAN/CVV copies are masked; status bodies and all unrelated values remain visible.",
  inputSchema: networkSchema,
  jsonInputSchema: {
    type: "object",
    required: ["session_id"],
    properties: {
      session_id: { type: "string" },
      since: { type: "integer", minimum: 0 },
      request_id: { type: "string" },
    },
  },
  annotations: { readOnlyHint: true },
  async handler(args, api, context) {
    return await (
      await import("./provision-drive.js")
    ).provisionNetworkTool.handler(args as never, api, context);
  },
};

export const provisionExtractTool: Tool = {
  name: "operate_extract",
  description:
    "Store a key by its source, never by its shape. Without capture, clicks the Copy " +
    "button in an open key dialog and returns what it writes to the clipboard as " +
    "{credentials: {api_key}}; page text is never scanned. When no Copy click yields a " +
    "value, nothing is stored and `error` says to read the page with operate_observe " +
    "and point capture at the key. Pass `store` to immediately save the value into the " +
    "Trusty Squire vault with the session's observed hosts as allowed_hosts seed; when " +
    "`store` is used, the response omits credential values and returns only vault " +
    "metadata. With `into_slot`, the copied value goes into a session slot instead.",
  inputSchema: extractSchema,
  jsonInputSchema: {
    type: "object",
    required: ["session_id"],
    properties: {
      session_id: { type: "string" },
      into_slot: { type: "string" },
      store: {
        type: "object",
        required: ["service"],
        properties: storeJsonProps,
      },
    },
  },
  async handler(args, api, context) {
    return await (
      await import("./provision-drive.js")
    ).provisionExtractTool.handler(args as never, api, context);
  },
};

export const operateLoginTool: Tool = {
  name: "operate_login",
  description:
    "Log in with provider + ref using the atomic OAuth flow; awaiting-human state is returned in this call. After a dispatched timeout or error, completion may be unknown: retain session_id and call operate_observe before another action; do not repeat OAuth blindly. " +
    "Drive the sealed username/password login lifecycle without exposing raw values. " +
    "action='prepare_signup' seals the user's captured email and a generated password; " +
    "'store_signup' vaults those prepared slots with the same login-host safeguards; " +
    "'load_saved' fetches an allowed saved login through encrypted browser-fill and seals " +
    "its fields into session slots. Use operate_type with slot to fill returned slots.",
  inputSchema: loginSchema,
  jsonInputSchema: {
    type: "object",
    oneOf: [
      {
        required: ["session_id", "provider", "ref"],
        properties: {
          session_id: { type: "string" },
          action: { const: "oauth" },
          provider: { type: "string", enum: ["google", "github"] },
          ref: { type: "string" },
        },
      },
      {
        required: ["action", "session_id"],
        properties: {
          action: { const: "prepare_signup" },
          session_id: { type: "string" },
          login_slot: { type: "string" },
          password_slot: { type: "string" },
          password_length: { type: "number" },
        },
      },
      {
        required: ["action", "session_id", "service", "login_hosts"],
        properties: {
          action: { const: "store_signup" },
          session_id: { type: "string" },
          service: { type: "string" },
          login_slot: { type: "string" },
          password_slot: { type: "string" },
          label: { type: "string" },
          signin_url: { type: "string" },
          login_hosts: { type: "array", items: { type: "string" } },
        },
      },
      {
        required: ["action", "session_id"],
        anyOf: [{ required: ["reference"] }, { required: ["service"] }],
        properties: {
          action: { const: "load_saved" },
          session_id: { type: "string" },
          reference: { type: "string" },
          service: { type: "string" },
          fields: vaultCredentialFieldsJson,
          slot_prefix: { type: "string" },
        },
      },
    ],
  },
  async handler(args, api, context) {
    return await (
      await import("./provision-drive.js")
    ).operateLoginTool.handler(args as never, api, context);
  },
};

export const operateNavigateTool: Tool = {
  name: "operate_navigate",
  description: "Navigate the session to a URL without session host restrictions.",
  inputSchema: navigateSchema,
  jsonInputSchema: {
    type: "object",
    required: ["session_id", "url"],
    properties: { ...sessionJson, url: { type: "string", format: "uri" } },
  },
  async handler(args, api, context) {
    return await (
      await import("./provision-drive.js")
    ).operateNavigateTool.handler(args as never, api, context);
  },
};

export const operateClickTool: Tool = {
  name: "operate_click",
  description:
    ACTION_FORMAT_NOTE +
    "Prefer a current observation ref or unique @label. If a screenshot-visible control has no usable ref, pass screenshot:{screenshot_id,x,y} from operate_screenshot.click_binding, in original image pixels. Provide exactly one of ref or screenshot. target_unresolved means the label was never issued in this document; stale_ref means its reference or alias expired. stale_screenshot requires a new image. Each image binding permits one DISPATCHED attempt; invalid_screenshot_point (a point outside the image or one that resolves no node) does not consume the binding, so a corrected point may retry the same image. After an uncertain click, observe before deciding any new action. If 3-D Secure bank approval is in progress, do not click, type, navigate, reload, resubmit, or trigger another verification. Only watch with operate_screenshot or operate_observe (short, non-blocking checks) until checkout resolves. Use inject_card for saved-card field entry. A pointer-interception failure may use guarded DOM dispatch internally only when the executor proves no click was dispatched.",
  inputSchema: clickSchema,
  jsonInputSchema: {
    type: "object",
    required: ["session_id"],
    oneOf: [
      { required: ["ref"], not: { required: ["screenshot"] } },
      { required: ["screenshot"], not: { required: ["ref"] } },
    ],
    properties: {
      ...sessionJson,
      ...refJson,
      format: actionFormatJson,
      screenshot: {
        type: "object",
        additionalProperties: false,
        required: ["screenshot_id", "x", "y"],
        properties: {
          screenshot_id: { type: "string", format: "uuid" },
          x: { type: "number", minimum: 0 },
          y: { type: "number", minimum: 0 },
        },
      },
    },
  },
  async handler(args, api, context) {
    return await (
      await import("./provision-drive.js")
    ).operateClickTool.handler(args as never, api, context);
  },
};

export const operateTypeTool: Tool = {
  name: "operate_type",
  description:
    ACTION_FORMAT_NOTE +
    "Fill a control with text, or a session slot returned by operate_login or operate_extract. Provide exactly one of text or slot. submit presses Enter after a successful fill.",
  inputSchema: typeSchema,
  jsonInputSchema: {
    type: "object",
    required: ["session_id", "ref"],
    oneOf: [
      { required: ["text"], not: { required: ["slot"] } },
      { required: ["slot"], not: { required: ["text"] } },
    ],
    properties: {
      ...sessionJson,
      ...refJson,
      text: { type: "string" },
      slot: { type: "string" },
      submit: { type: "boolean" },
      format: actionFormatJson,
    },
  },
  async handler(args, api, context) {
    return await (
      await import("./provision-drive.js")
    ).operateTypeTool.handler(args as never, api, context);
  },
};

export const operateSelectTool: Tool = {
  name: "operate_select",
  description:
    ACTION_FORMAT_NOTE +
    "Choose an option by visible text with ref + values (one value per control). For several controls, supply an ordered selections map of ref to option; partial results are retained. country selects the phone field's native country dropdown.",
  inputSchema: selectSchema,
  jsonInputSchema: {
    type: "object",
    required: ["session_id"],
    oneOf: [
      {
        required: ["ref", "values"],
        not: { anyOf: [{ required: ["selections"] }, { required: ["country"] }] },
      },
      {
        required: ["selections"],
        not: {
          anyOf: [{ required: ["ref"] }, { required: ["values"] }, { required: ["country"] }],
        },
      },
      {
        required: ["country"],
        not: {
          anyOf: [{ required: ["ref"] }, { required: ["values"] }, { required: ["selections"] }],
        },
      },
    ],
    properties: {
      ...sessionJson,
      ...refJson,
      values: { type: "array", items: { type: "string" }, minItems: 1, maxItems: 1 },
      selections: { type: "object", additionalProperties: { type: "string" } },
      country: { type: "string" },
      format: actionFormatJson,
    },
  },
  async handler(args, api, context) {
    return await (
      await import("./provision-drive.js")
    ).operateSelectTool.handler(args as never, api, context);
  },
};

export const operateUploadTool: Tool = {
  name: "operate_upload",
  description:
    "Attach a local file through the browser file chooser. The file must exist on the machine running the browser. Target a current ref or @label for the upload button or file input; path must be absolute.",
  inputSchema: uploadSchema,
  jsonInputSchema: {
    type: "object",
    required: ["session_id", "target", "path"],
    properties: {
      ...sessionJson,
      target: { type: "string" },
      path: { type: "string", pattern: "^/" },
      format: actionFormatJson,
    },
  },
  async handler(args, api, context) {
    return await (
      await import("./provision-drive.js")
    ).operateUploadTool.handler(args as never, api, context);
  },
};

export const operatePressTool: Tool = {
  name: "operate_press",
  description:
    ACTION_FORMAT_NOTE +
    "Press a keyboard key in the current session, such as Enter, Tab, or Escape.",
  inputSchema: pressSchema,
  jsonInputSchema: {
    type: "object",
    required: ["session_id", "key"],
    properties: {
      ...sessionJson,
      key: { type: "string" },
      format: actionFormatJson,
    },
  },
  async handler(args, api, context) {
    return await (
      await import("./provision-drive.js")
    ).operatePressTool.handler(args as never, api, context);
  },
};

export const operateScrollTool: Tool = {
  name: "operate_scroll",
  description:
    ACTION_FORMAT_NOTE +
    "Scroll the page viewport down, up, to the bottom, or to the top. Observe again to discover newly visible controls.",
  inputSchema: scrollSchema,
  jsonInputSchema: {
    type: "object",
    required: ["session_id"],
    properties: {
      ...sessionJson,
      direction: { type: "string", enum: ["down", "up", "bottom", "top"], default: "down" },
      format: actionFormatJson,
    },
  },
  async handler(args, api, context) {
    return await (
      await import("./provision-drive.js")
    ).operateScrollTool.handler(args as never, api, context);
  },
};

export const operateWaitTool: Tool = {
  name: "operate_wait",
  description:
    ACTION_FORMAT_NOTE +
    "Wait briefly for the live page to change, then return a fresh observation. Use this for spinners, late-mounted fields, and pending requests without assigning them a payment stage.",
  inputSchema: waitSchema,
  jsonInputSchema: {
    type: "object",
    required: ["session_id"],
    properties: {
      ...sessionJson,
      milliseconds: { type: "integer", minimum: 0, maximum: 30_000, default: 1_000 },
      format: actionFormatJson,
    },
  },
  async handler(args, api, context) {
    return await (
      await import("./provision-drive.js")
    ).operateWaitTool.handler(args as never, api, context);
  },
};

export const operateReadInboxTool: Tool = {
  name: "operate_read_inbox",
  description:
    "Read verification mail in a separate tab without changing the live form. Returns {code, link, source_from} or needs_user. " +
    "The default search uses the session recipient and service host; sender and recipient narrow it. " +
    "For an IP or localhost start URL, host scoping is unavailable: check source_from before using the result. " +
    "It checks search and All Mail because Gmail search can lag. A miss reports the query; retry after a few seconds. " +
    "into_slot keeps a found code in a session slot for operate_type; grant_inbox_consent overrides consent for this call. " +
    "If needs_user reports wall:google_session, ask the user to run connect; polling will not clear it.",
  inputSchema: readInboxSchema,
  jsonInputSchema: {
    type: "object",
    required: ["session_id"],
    properties: {
      session_id: { type: "string" },
      sender: { type: "string" },
      recipient: { type: "string" },
      into_slot: { type: "string" },
      grant_inbox_consent: { type: "boolean" },
    },
  },
  annotations: { readOnlyHint: true },
  async handler(args, api, context) {
    return await (
      await import("./provision-drive.js")
    ).operateReadInboxTool.handler(args as never, api, context);
  },
};

export const operateFinishTool: Tool = {
  name: "operate_finish",
  jsonOutputSchema: {
    type: "object",
    required: ["session_id", "operation_id", "execution", "mutation", "cleanup", "closed"],
    properties: {
      session_id: { type: "string" },
      operation_id: { type: "string" },
      execution: { type: "string", enum: ["completed", "cancelled", "pending", "unknown"] },
      mutation: { type: "string", enum: ["not_dispatched", "dispatched", "unknown"] },
      cleanup: { type: "string", enum: ["open", "closing", "closed", "already_closed", "unknown"] },
      closed: { type: "boolean" },
      data: { type: "object", additionalProperties: { type: ["string", "number", "boolean"] } },
    },
    additionalProperties: true,
  },
  description:
    "Finish the task and close its session. outcome='none' closes without a reported outcome; 'result' reports summary or data — the reported outcome is recorded as-is. Extract and store credentials with operate_extract({store}) before calling operate_finish. Deprecated outcome='credentials' returns an error and will be removed next minor. Successful completion saves eligible login state through the existing teardown.",
  inputSchema: publicFinishSchema,
  jsonInputSchema: {
    type: "object",
    required: ["session_id"],
    properties: {
      ...sessionJson,
      outcome: {
        type: "string",
        enum: ["none", "result", "credentials"],
        default: "none",
        description:
          "credentials is deprecated and rejected; use operate_extract({store}) then operate_finish",
      },
      store: {
        type: "object",
        deprecated: true,
        description: "Deprecated with outcome=credentials; removed next minor",
      },
      summary: { type: "string" },
      data: { type: "object" },
    },
    allOf: [
      {
        if: { required: ["outcome"], properties: { outcome: { const: "result" } } },
        then: { anyOf: [{ required: ["summary"] }, { required: ["data"] }] },
      },
    ],
  },
  async handler(args, api, context) {
    return await (
      await import("./provision-drive.js")
    ).operateFinishTool.handler(args as never, api, context);
  },
};

export const operateDriveTool: Tool = {
  name: "operate_drive",
  description:
    "Drive a multi-step signup, checkout, or other website goal and hand back when complete, blocked, or out of budget. " +
    "For a known multi-step goal, pass url, goal, and all known facts directly; this skips the initial general observation. Use session_id to resume the same session. " +
    "Identity and payment values must come from facts; a search phrase may come from the goal. " +
    "Amount_cents is in the currency's smallest unit: USD $12.34 -> 1234; JPY ¥65,800 -> 65800 (do not multiply by 100); KRW works like JPY. " +
    "The loop can handle Google sign-in, verification mail, captcha, and card release. " +
    "max_steps (default 60) and max_seconds (default 45) bound a call. Resume a budget or other partial handoff on the " +
    "same session with added facts and/or answer from its options. The handoff includes status, current compact observation, " +
    "trajectory, done/remaining, and counters. complete means done; needs_value names a missing field; stuck and low_confidence " +
    "need a decision. invalid_answer, no_progress, budget, evaluate_timeout, pending_approval, and " +
    "card_incomplete are resumable. After a card_incomplete handoff, retry against the same approval_id. " +
    "Always operate_finish when done.",
  inputSchema: driveSchema,
  jsonInputSchema: {
    type: "object",
    required: ["goal"],
    oneOf: [{ required: ["session_id"] }, { required: ["url"] }],
    properties: {
      session_id: { type: "string" },
      url: { type: "string", format: "uri" },
      goal: { type: "string" },
      facts: { type: "object", additionalProperties: { type: "string" } },
      max_steps: { type: "integer", minimum: 1, maximum: 60 },
      max_seconds: { type: "integer", minimum: 1, maximum: 120 },
      answer: { type: "string" },
    },
  },
  async handler(args, api, context) {
    return await (
      await import("./provision-drive.js")
    ).operateDriveTool.handler(args as never, api, context);
  },
};

export const OPERATE_TOOLS: Tool[] = [
  provisionStartTool,
  operateDriveTool,
  operateFinishTool,
  provisionObserveTool,
  provisionScreenshotTool,
  provisionNetworkTool,
  operateNavigateTool,
  operateClickTool,
  operateTypeTool,
  operateSelectTool,
  operateUploadTool,
  operatePressTool,
  operateScrollTool,
  operateWaitTool,
  operateReadInboxTool,
  operateLoginTool,
  provisionExtractTool,
] as Tool[];

const captureOutputSchema = {
  type: "object" as const,
  properties: {
    session_id: { type: "string" },
    operation_id: { type: "string" },
    write_id: { type: "string" },
    execution: { enum: ["completed", "cancelled", "pending", "unknown"] },
    mutation: { enum: ["not_dispatched", "dispatched", "unknown"] },
    cleanup: { enum: ["open", "closing", "closed", "already_closed", "unknown"] },
    closed: { type: "boolean" },
    stored: { type: "boolean" },
    storage: { enum: ["stored", "unknown", "not_attempted"] },
    stored_credential: {
      type: "object",
      properties: { reference: { type: "string" } },
      additionalProperties: true,
    },
    resolved_source: {
      type: "object",
      description: "Names the element the vaulted value was resolved from (role/name or selector).",
      additionalProperties: true,
    },
    candidate_count: { type: "integer" },
    found: {
      type: "array",
      maxItems: 12,
      items: {
        type: "object",
        required: ["role"],
        additionalProperties: false,
        properties: {
          role: { type: "string" },
          name: { type: ["string", "null"] },
        },
      },
    },
    action_result: { type: "object", additionalProperties: true },
    retry: { enum: ["extract_only", "action"] },
  },
  additionalProperties: true,
};

for (const tool of OPERATE_TOOLS) {
  if (
    ![
      "operate_click",
      "operate_type",
      "operate_select",
      "operate_press",
      "operate_extract",
    ].includes(tool.name)
  )
    continue;
  const properties = tool.jsonInputSchema.properties;
  const supportsCapture = tool.name === "operate_click" || tool.name === "operate_extract";
  if (properties !== null && typeof properties === "object")
    Object.assign(properties, {
      capture: supportsCapture
        ? captureJsonFor(tool.name)
        : {
            type: "object",
            deprecated: true,
            description:
              "Deprecated and rejected; perform the action, then call operate_extract({capture}). Removed next minor.",
          },
    });
  tool.description += supportsCapture
    ? CAPTURE_NOTE +
      (tool.name === "operate_click" ? CLICK_CAPTURE_NOTE : "") +
      (tool.name === "operate_extract" ? EXTRACT_CAPTURE_NOTE : "")
    : " Deprecated capture is rejected; perform the action, then call operate_extract({capture}). Removed next minor.";
  if (supportsCapture) tool.jsonOutputSchema = captureOutputSchema;
}

// Keep the additive click receipt discoverable alongside the shared capture result.
operateClickTool.jsonOutputSchema = {
  ...captureOutputSchema,
  properties: {
    ...captureOutputSchema.properties,
    screenshot_click: {
      type: "object",
      required: ["dispatch", "outcome", "retry_policy"],
      properties: {
        dispatch: { enum: ["dispatched", "not_dispatched", "unknown"] },
        outcome: { const: "unknown" },
        retry_policy: { enum: ["observe_before_new_action", "capture_new_screenshot"] },
      },
    },
  },
};
