import { Buffer } from "node:buffer";
import { createHmac, randomBytes } from "node:crypto";
import type { InteractiveElement } from "./browser.js";
import { browserUseBoundedContextText, type BrowserUseNode } from "./browser-use-serializer.js";

export const OBSERVE_V2_MAX_WIRE_BYTES = 4_096;
export const OBSERVE_V2_MAX_TOKENS = 1_024;

export function compactV2PayloadWithinBudget(payload: unknown): boolean {
  const bytes = Buffer.byteLength(JSON.stringify(payload), "utf8");
  if (bytes > OBSERVE_V2_MAX_WIRE_BYTES) return false;
  // Token estimate at the ~4 bytes/token the wire's enum-only prose runs.
  // Comparing raw BYTES against the token cap (the old behavior) made the
  // effective budget 1024 bytes, so a real-world OAuth-shaped URL alone
  // hard-failed observation — the live "compact-v2 budget metadata exceeded"
  // session killer. The byte cap bounds the MCP message; the token cap bounds
  // model context, and both now scale with the page instead of strangling it.
  return Math.ceil(bytes / 4) <= OBSERVE_V2_MAX_TOKENS;
}

/**
 * Graceful degradation for a payload whose FIXED metadata (url, semantic
 * context, start hints) alone exceeds the wire budget. Degrades in order:
 * shrink the URL, drop the semantic title/heading, drop start-routing hints —
 * never the safe_table rows or the overflow cursor, which are the actionable
 * map. Returns null only when code-owned fields (session id / cursor) are
 * themselves hostile, which the caller fails closed on.
 */
export function compactV2DegradeMetadata(
  payload: Record<string, unknown>,
): Record<string, unknown> | null {
  if (compactV2PayloadWithinBudget(payload)) return payload;
  let candidate = payload;
  for (const urlCap of [512, 128]) {
    const url = typeof candidate.url === "string" ? candidate.url : "";
    if (url.length > urlCap) candidate = { ...candidate, url: url.slice(0, urlCap) };
    if (compactV2PayloadWithinBudget(candidate)) return candidate;
  }
  if ("semantic" in candidate) {
    const semantic = candidate.semantic;
    if (
      typeof semantic === "object" &&
      semantic !== null &&
      Array.isArray((semantic as { blockers?: unknown }).blockers) &&
      (semantic as { blockers: unknown[] }).blockers.length > 0
    ) {
      candidate = {
        ...candidate,
        semantic: { blocked: true, blockers: (semantic as { blockers: unknown[] }).blockers },
      };
    } else {
      const rest = { ...candidate };
      delete rest.semantic;
      candidate = rest;
    }
    if (compactV2PayloadWithinBudget(candidate)) return candidate;
  }
  if ("hint" in candidate || "user_email" in candidate || "hint_overflow" in candidate) {
    const rest = { ...candidate };
    delete rest.hint;
    delete rest.user_email;
    delete rest.hint_overflow;
    candidate = rest;
    if (compactV2PayloadWithinBudget(candidate)) return candidate;
  }
  if ("semantic" in candidate) {
    const rest = { ...candidate };
    delete rest.semantic;
    candidate = rest;
    if (compactV2PayloadWithinBudget(candidate)) return candidate;
  }
  return null;
}

export type SafeRoleV2 =
  | "button"
  | "link"
  | "textbox"
  | "select"
  | "checkbox"
  | "radio"
  | "tab"
  | "menuitem"
  | "file"
  | (string & {});
export type SafeIntentV2 =
  | "search"
  | "close"
  | "next"
  | "previous"
  | "submit"
  | "continue"
  | "login"
  | "signup"
  | "add_to_cart"
  | "view_cart"
  | "checkout"
  | "payment"
  | "destructive";
// These semantic classes are generated by TS, never page-provided labels. They
// make the action map useful for forms without changing the page content in the
// emitted DOM.
export type SafeFieldV2 =
  | "email"
  | "password"
  | "username"
  | "name"
  | "phone"
  | "search"
  | "address"
  | "city"
  | "region"
  | "postal"
  | "country"
  | "date"
  | "quantity"
  | "promo"
  | "payment";
export type SafeStageV2 = "browse" | "auth" | "form" | "cart" | "checkout" | "complete";
export type SafeQueryMatchV2 = "name" | "role" | "text" | "context";

export interface SafeControlV2 {
  ref: string;
  role: SafeRoleV2;
  state?: string;
  visibility: "viewport" | "near";
  action?: SafeIntentV2;
  field?: SafeFieldV2;
  /**
   * The legible alias the agent may target instead of `ref` (`@email-address`).
   * Slugified from the control's accessible name; never a field value.
   */
  label?: string;
  choice?: string;
  frame: "main" | "same_origin" | "cross_origin";
  /** Query-only match provenance; absent from the default action map. */
  match?: SafeQueryMatchV2;
}

/** Raw DOM input is accepted only from title and visible heading elements. */
export interface ObservationSemanticSourceV2 {
  title: string;
  headings: readonly string[];
}

export interface SafePageSemanticsV2 {
  title?: string;
  headings?: string[];
  blockers?: SafeBlockerV2[];
  /** Observed blocker evidence; independent of inferred page stage. */
  blocked?: true;
}

export interface SafeBlockerV2 {
  kind: "challenge" | "validation";
  text: string;
  ref?: string;
  target?: "unavailable";
  focus?: "focused" | "focusable";
  keyboard?: "space" | "tab_space";
  // Present only when the observation's request-scope denials include
  // challenge-related hosts (Clerk bot protection, Cloudflare Turnstile,
  // hCaptcha, reCAPTCHA): the on-page challenge cannot complete inside the
  // session scope, so restarting the session with those hosts allowed is the
  // remedy — clicking the widget again can never succeed.
  cause?: "scope";
  cause_hosts?: string[];
}

/**
 * The observed document version an act is authorized against
 * (docs/observation-model.md §4.1). `doc` is an internal HMAC of the browser's
 * stable main-document identity; `rev` is a monotonic counter that advances
 * whenever the skeleton is re-serialized after a DOM mutation. A `doc` change
 * (a real navigation) invalidates every ref minted under it; a `rev` change is
 * benign and only re-binds paging cursors.
 */
export interface ObservationEpochV2 {
  doc: string;
  rev: number;
}

export interface SafeObservationIndexV2 {
  epoch: ObservationEpochV2;
  stage: SafeStageV2;
  semantics: SafePageSemanticsV2;
  rows: SafeControlV2[];
  byRef: Map<string, string>;
  expiresAt: number;
}

/**
 * The V2 state retained between observations: generation-bound action-map
 * entries and the previously emitted canonical DOM for delta comparison.
 */
export interface SafeObservationBaselineV2 {
  epoch: ObservationEpochV2;
  stage: SafeStageV2;
  semantics: SafePageSemanticsV2;
  byRef: Map<string, SafeControlV2>;
  /** Last emitted canonical tree and its rendered stable identities. */
  dom?: string;
  renderedRefs?: string[];
}

export const COMPACT_V2_HANDLE_LENGTH = 22;
const COMPACT_V2_HANDLE_RE = new RegExp(`^@e:[A-Za-z0-9_-]{${COMPACT_V2_HANDLE_LENGTH}}$`);

export class StableObservationRefs {
  private document: string | undefined;
  private generation = 0;
  private refs = new Map<string, string>();
  private identities = new Map<string, string>();
  private anchors = new Map<string, { intent: string; ref: string }>();
  private aliases = new Map<string, string>();
  private aliasOwners = new Map<string, string>();
  private reset(document: string): void {
    if (this.document === document) return;
    this.document = document;
    this.generation++;
    this.refs.clear();
    this.identities.clear();
    this.anchors.clear();
    this.aliases.clear();
    this.aliasOwners.clear();
  }

  /** Reconcile the full live inventory, retiring absent or materially changed nodes. */
  actions(
    document: string,
    elements: readonly InteractiveElement[],
  ): Map<InteractiveElement, string> {
    this.reset(document);
    const present = new Set(elements.map((el) => el.observationIdentity));
    for (const identity of this.anchors.keys()) {
      if (!present.has(identity)) this.anchors.delete(identity);
    }
    const counts = new Map<string, number>();
    for (const el of elements) {
      if (el.observationIdentity)
        counts.set(el.observationIdentity, (counts.get(el.observationIdentity) ?? 0) + 1);
    }
    const handles = new Map<InteractiveElement, string>();
    for (const el of elements) {
      const identity = el.observationIdentity;
      if (!identity || el.observationIntent === undefined || counts.get(identity) !== 1) {
        if (identity) this.anchors.delete(identity);
        continue;
      }
      let anchor = this.anchors.get(identity);
      if (!anchor || anchor.intent !== el.observationIntent) {
        anchor = {
          intent: el.observationIntent,
          ref: this.get(document, `action:${randomBytes(32).toString("base64url")}`),
        };
        this.anchors.set(identity, anchor);
      }
      handles.set(el, anchor.ref);
    }
    return handles;
  }

  /** Distinguish an unknown label from a retired alias in this document. */
  hasLabel(label: string): boolean {
    return this.aliasOwners.has(label);
  }

  /** Compatibility spelling of one capability; never reassign an old alias. */
  label(ref: string, preferred: string | undefined): string | undefined {
    const existing = this.aliases.get(ref);
    if (existing !== undefined || preferred === undefined) return existing;
    let candidate = preferred;
    for (let suffix = 2; this.aliasOwners.has(candidate); suffix++)
      candidate = labelWithOrdinalV2(preferred, suffix);
    this.aliases.set(ref, candidate);
    this.aliasOwners.set(candidate, ref);
    return candidate;
  }

  constructor(private readonly secret: Buffer<ArrayBufferLike> = randomBytes(32)) {}
  get(document: string, identity: string): string {
    this.reset(document);
    let ref = this.refs.get(identity);
    if (ref === undefined) {
      for (let collision = 0; ; collision++) {
        const candidate = `@e:${createHmac("sha256", this.secret)
          .update(document)
          .update("\u0000")
          .update(String(this.generation))
          .update("\u0000")
          .update(identity)
          .update("\u0000")
          .update(String(collision))
          .digest("base64url")
          .slice(0, COMPACT_V2_HANDLE_LENGTH)}`;
        const owner = this.identities.get(candidate);
        if (owner === undefined || owner === identity) {
          ref = candidate;
          this.identities.set(ref, identity);
          break;
        }
      }
      this.refs.set(identity, ref);
    }
    return ref;
  }
}
const LABEL_MAX_CHARS = 32;
const COMPACT_V2_LABEL_RE = /^@[\p{L}\p{M}\p{N}]+(?:-[\p{L}\p{M}\p{N}]+)*(?:…)?$/u;

export function isCompactV2Handle(target: string): boolean {
  return COMPACT_V2_HANDLE_RE.test(target);
}

/** The `@label` alias form, distinguishable from a handle by its `@e:` prefix. */
export function isCompactV2Label(target: string): boolean {
  return (
    COMPACT_V2_LABEL_RE.test(target) &&
    /[\p{L}\p{N}]/u.test(target) &&
    Array.from(target.slice(1)).length <= LABEL_MAX_CHARS
  );
}

/**
 * Resolve a handle only when it is well-formed AND a member of the current
 * snapshot's action map. Callers must never turn an unknown @e: value into a
 * label or legacy-ref lookup. The handle is document-scoped by construction
 * (the allocator retires its document map), so a ref from a replaced document finds no
 * live match rather than resolving onto whatever now occupies its position.
 */
export function compactV2LegacyRefForHandle(
  handles: ReadonlyMap<string, string>,
  target: string,
): string | null {
  if (!isCompactV2Handle(target)) return null;
  return handles.get(target) ?? null;
}

/**
 * Split a glued "Title + description" accessible name into its leading title,
 * detected from the ORIGINAL name — by slug time the boundary is gone. The
 * 2026-09-06 ipinfo docs dogfood produced labels like
 * `@database-downloadsdownload-ip-da`: two headings (or a heading and its
 * description) concatenated by the DOM with no whitespace, slugified into one
 * unreadable run and hard-cut mid-word. The boundaries that mark that seam in
 * the original name are:
 * - a newline inside the accessible name,
 * - sentence/heading punctuation (`.` `!` `?` `:` `)`) directly abutting the
 *   next word (`(Search Ctrl+K)Navigation`, `Docs.Start here`) — a period
 *   followed by a lowercase letter ("Node.js") is NOT a boundary,
 * - a lowercase→uppercase case transition where two headings were joined
 *   with no space (`DownloadsDownload`).
 * Returns the original name when no qualifying boundary is found, so ordinary
 * multi-word names and short glued pairs keep their full slug.
 */
function leadingTitleFromAccessibleName(name: string): string {
  // A candidate title must read as a heading — multi-word, or a substantial
  // standalone word — so camelCase identifiers ("myAccountSettings") and
  // abbreviation fragments ("U.S. Government") keep their full slug, and a
  // real description must remain behind the seam.
  const readsAsHeading = (title: string): boolean =>
    /[A-Za-z0-9]/.test(title) && (title.includes(" ") || title.length >= 5);
  const hasDescription = (rest: string): boolean => /[A-Za-z0-9].*[A-Za-z0-9]/.test(rest);
  for (let i = 0; i < name.length - 1; i += 1) {
    const ch = name[i]!;
    const next = name[i + 1]!;
    if (ch === "\n") {
      if (readsAsHeading(name.slice(0, i)) && hasDescription(name.slice(i + 1))) {
        return name.slice(0, i);
      }
      continue;
    }
    if (".!?:)".includes(ch) && /[A-Za-z0-9]/.test(next)) {
      // A period followed by a lowercase letter is an abbreviation
      // ("Node.js"), not a heading seam; require an uppercase letter (or a
      // closing parenthesis, which abuts a seam regardless of case).
      if ((ch === ")" || /[A-Z]/.test(next)) && hasDescription(name.slice(i + 1))) {
        const title = name.slice(0, i);
        if (readsAsHeading(title)) return title;
      }
      continue;
    }
    if (/[a-z]/.test(ch) && /[A-Z]/.test(next)) {
      const title = name.slice(0, i + 1);
      if (readsAsHeading(title) && hasDescription(name.slice(i + 1))) return title;
    }
  }
  return name;
}

/** Addressable slug of the page's control description, with the existing title and length limits. */
export function controlLabelV2(description: string | undefined): string | undefined {
  if (description === undefined) return undefined;
  const titled = leadingTitleFromAccessibleName(description);
  let slug = titled
    .normalize("NFKC")
    .toLowerCase()
    .replace(/[^\p{L}\p{M}\p{N}]+/gu, "-")
    .replace(/^-+|-+$/gu, "");
  let characters = Array.from(slug);
  const truncated = characters.length > LABEL_MAX_CHARS;
  const usesUnicode = characters.some((character) => character.charCodeAt(0) > 0x7f);
  if (truncated) {
    characters = characters.slice(0, LABEL_MAX_CHARS - Number(usesUnicode));
    // Never cut mid-word: drop the trailing partial segment at the last word
    // boundary. A single unbroken run longer than the budget keeps its
    // mid-run cut — there is no boundary to cut on.
    const lastBoundary = characters.lastIndexOf("-");
    if (lastBoundary > 0) characters = characters.slice(0, lastBoundary);
  }
  slug = characters.join("").replace(/-+$/g, "");
  if (slug.length === 0 || !/[\p{L}\p{N}]/u.test(slug)) return undefined;
  return `@${slug}${truncated && usesUnicode ? "…" : ""}`;
}

function labelWithOrdinalV2(label: string, suffix: number): string {
  const tail = `-${suffix}`;
  const characters = Array.from(label.slice(1));
  const truncated =
    characters.length > LABEL_MAX_CHARS - Array.from(tail).length || characters.at(-1) === "…";
  const body = truncated ? characters.slice(0, -1) : characters;
  const limit = LABEL_MAX_CHARS - Array.from(tail).length - Number(truncated);
  return `@${body.slice(0, limit).join("")}${tail}${truncated ? "…" : ""}`;
}

type WireControlV2 = [string, string, string?];

// The protocol is intentionally positional to keep repeated observes small.
// Tuple schema: [ref, role(b/l/t/s/c/r/tb/m/f), optional compact description].
// The description starts with the `@label` alias (itself a valid act target)
// and appends only present code-owned facts (`s=`, `a=`, `f=`, `q=`, `x=`,
// and query-only `m=` provenance). It
// is deliberately one sparse string rather than nullable columns:
// checked/unchecked, disabled, action, field, card choice, and frame context
// remain distinguishable without paying for empty slots on every row. The
// label grammar excludes `|` and `=`, so no escaping is needed.
function wireControl(row: SafeControlV2): WireControlV2 {
  const role: Record<SafeRoleV2, string> = {
    button: "b",
    link: "l",
    textbox: "t",
    select: "s",
    checkbox: "c",
    radio: "r",
    tab: "tb",
    menuitem: "m",
    file: "f",
  };
  const facts = [
    row.label,
    ...(row.visibility === "near" ? ["v=offscreen"] : []),
    ...(row.state === undefined ? [] : [`s=${row.state}`]),
    ...(row.action === undefined ? [] : [`a=${row.action}`]),
    ...(row.field === undefined ? [] : [`f=${row.field}`]),
    ...(row.choice === undefined ? [] : [`q=${row.choice}`]),
    ...(row.frame === "main" ? [] : [`x=${row.frame === "same_origin" ? "s" : "x"}`]),
    ...(row.match === undefined
      ? []
      : [`m=${{ name: "n", role: "r", text: "t", context: "c" }[row.match]}`]),
  ].filter((value): value is string => value !== undefined);
  return facts.length === 0
    ? [row.ref, Object.hasOwn(role, row.role) ? role[row.role]! : row.role]
    : [row.ref, Object.hasOwn(role, row.role) ? role[row.role]! : row.role, facts.join("|")];
}

const SAFE_DESCRIPTION_MAX_CHARS = 40;
// There is NO description screening on the observation path. Every string a
// page renders — OAuth button copy, an email address, a Gmail subject line, a
// street address, a rendered API key, a card number — is content the driving
// agent needs to read. The only transform left is truncation, which is the
// compactness budget, not masking.
const CARD_SECURITY_VALUE_RE = /\b(?:cvv|cvc|security\s*code)\s*[:#-]?\s*\d{3,4}\b/i;
const PAN_MAX_SPAN_CHARS = 96;

function luhnValid(digits: string): boolean {
  let sum = 0;
  let double = false;
  for (let index = digits.length - 1; index >= 0; index -= 1) {
    let digit = Number(digits[index]);
    if (double) {
      digit *= 2;
      if (digit > 9) digit -= 9;
    }
    sum += digit;
    double = !double;
  }
  return sum % 10 === 0;
}

/** A rendered card number: 13-19 digits in one span that passes Luhn. */
function containsLuhnPan(value: string): boolean {
  const positions = Array.from(value.matchAll(/\d/g), (match) => match.index);
  for (let start = 0; start + 13 <= positions.length; start += 1) {
    const maxLength = Math.min(19, positions.length - start);
    for (let length = 13; length <= maxLength; length += 1) {
      const span = positions.slice(start, start + length);
      if (span[span.length - 1]! - span[0]! + 1 > PAN_MAX_SPAN_CHARS) break;
      if (luhnValid(span.map((position) => value[position]).join(""))) return true;
    }
  }
  return false;
}

/**
 * Card material, used ONLY by the recordable-token screen below (the operator's
 * stderr audit trail and the action trace a capture publishes to the SHARED
 * skill registry). It is never applied to what the agent is shown.
 */
function carriesPaymentMaterial(value: string): boolean {
  return containsLuhnPan(value) || CARD_SECURITY_VALUE_RE.test(value);
}

// ---- Recordable-token screen (NOT observation redaction) -------------------
// Two surfaces are not the agent's view of the page and keep their original
// closed-vocabulary screen: the operator's structured stderr audit trail, and
// the recorded action trace that a captured run publishes to the SHARED skill
// registry. Both cross a boundary the payment-only observation policy says
// nothing about — one is a log, the other is cross-user institutional memory —
// so a page-derived string still has to be recognizable code-owned vocabulary
// before it lands there. Never use this to screen what `operate_observe`,
// `operate_observe_query`, or `operate_screenshot` shows the driving agent.
const RECORDABLE_TOKEN_MAX_CHARS = 40;
const RECORDABLE_EMAIL_RE = /\b[A-Z0-9._%+-]+@[A-Z0-9.-]+\.[A-Z]{2,}\b/i;
const RECORDABLE_SECRET_ASSIGNMENT_RE =
  /\b(?:password|passcode|token|api[_ -]?key|secret)\b\s*[:=]\s*\S{4,}/i;
const RECORDABLE_HIGH_ENTROPY_RE = /\b[A-Za-z0-9_-]{24,}\b/;
const RECORDABLE_GRAMMAR_RE = /^[\p{L}\p{N}][\p{L}\p{N}\s&'’+,.!?():=/@_$|-]*$/u;
const RECORDABLE_WORDS = new Set([
  "a",
  "access",
  "account",
  "add",
  "address",
  "an",
  "and",
  "api",
  "back",
  "bag",
  "basket",
  "billing",
  "button",
  "cancel",
  "card",
  "cart",
  "choose",
  "checkout",
  "city",
  "close",
  "code",
  "confirm",
  "contact",
  "continue",
  "control",
  "controls",
  "copy",
  "country",
  "create",
  "customer",
  "date",
  "dense",
  "delivery",
  "details",
  "different",
  "discount",
  "dismiss",
  "done",
  "economy",
  "email",
  "example",
  "express",
  "external",
  "first",
  "finish",
  "form",
  "free",
  "gift",
  "google",
  "ground",
  "in",
  "item",
  "key",
  "large",
  "log",
  "login",
  "merchant",
  "method",
  "name",
  "native",
  "next",
  "no",
  "now",
  "option",
  "order",
  "overnight",
  "page",
  "password",
  "pay",
  "payment",
  "phone",
  "pickup",
  "postal",
  "previous",
  "priority",
  "private",
  "proceed",
  "product",
  "promo",
  "quantity",
  "rate",
  "region",
  "register",
  "registration",
  "review",
  "save",
  "sample",
  "search",
  "secure",
  "select",
  "serialized",
  "shipping",
  "sign",
  "signup",
  "size",
  "standard",
  "storefront",
  "style",
  "submit",
  "terms",
  "thanks",
  "to",
  "token",
  "united",
  "username",
  "variant",
  "verification",
  "view",
  "with",
  "workspace",
  "your",
]);

function hasRecordableGrammar(value: string): boolean {
  if (!RECORDABLE_GRAMMAR_RE.test(value)) return false;
  const words = value.match(/[\p{L}\p{N}]+/gu) ?? [];
  return (
    words.length > 0 &&
    words.every((word) => RECORDABLE_WORDS.has(word.toLowerCase()) || /^\d{1,6}$/.test(word))
  );
}

/**
 * The screen for the audit trail and the registry-bound action trace. Returns
 * `undefined` for anything outside the code-owned vocabulary; callers turn that
 * into `<sealed>` or refuse to record the action.
 */
export function recordableTokenV2(value: string | null | undefined): string | undefined {
  if (typeof value !== "string") return undefined;
  const normalized = value.replace(/\s+/g, " ").trim();
  if (
    normalized.length === 0 ||
    !hasRecordableGrammar(normalized) ||
    carriesPaymentMaterial(normalized) ||
    normalized.replace(/\D/g, "").length >= 13 ||
    RECORDABLE_EMAIL_RE.test(normalized) ||
    RECORDABLE_SECRET_ASSIGNMENT_RE.test(normalized) ||
    RECORDABLE_HIGH_ENTROPY_RE.test(normalized)
  ) {
    return undefined;
  }
  return normalized.length <= RECORDABLE_TOKEN_MAX_CHARS
    ? normalized
    : `${normalized.slice(0, RECORDABLE_TOKEN_MAX_CHARS - 1)}…`;
}

/**
 * Normalize and length-budget a page-derived description for the wire row. It
 * rejects nothing: the truncation is the compactness budget, not redaction.
 */
export function safeDescriptionV2(value: string | null | undefined): string | undefined {
  const normalized = normalizeDescriptionV2(value);
  if (normalized === undefined) return undefined;
  return normalized.length <= SAFE_DESCRIPTION_MAX_CHARS
    ? normalized
    : `${normalized.slice(0, SAFE_DESCRIPTION_MAX_CHARS - 1)}…`;
}

/** Normalize page descriptions without applying the query row's length limit. */
export function normalizeDescriptionV2(value: string | null | undefined): string | undefined {
  if (typeof value !== "string") return undefined;
  // Control characters would break the positional wire encoding; they are not
  // page copy, so dropping them is formatting rather than masking.
  const normalized = value
    .replace(/[\p{Cc}\p{Cf}]/gu, " ")
    .replace(/\s+/g, " ")
    .trim();
  return normalized.length === 0 ? undefined : normalized;
}

const SAFE_AUTOCOMPLETE_TOKENS = new Set([
  "address-level1",
  "address-level2",
  "address-line1",
  "address-line2",
  "address-line3",
  "bday",
  "bday-day",
  "bday-month",
  "bday-year",
  "cc-csc",
  "cc-exp",
  "cc-exp-month",
  "cc-exp-year",
  "cc-name",
  "cc-number",
  "country",
  "country-name",
  "current-password",
  "email",
  "family-name",
  "given-name",
  "honorific-prefix",
  "honorific-suffix",
  "name",
  "new-password",
  "nickname",
  "one-time-code",
  "organization",
  "organization-title",
  "postal-code",
  "shipping",
  "street-address",
  "tel",
  "tel-area-code",
  "tel-country-code",
  "tel-extension",
  "tel-local",
  "tel-local-prefix",
  "tel-local-suffix",
  "tel-national",
  "transaction-amount",
  "transaction-currency",
  "username",
]);

function safeAutocompleteV2(value: string | null | undefined): string | null {
  if (typeof value !== "string") return null;
  const tokens = value.toLowerCase().trim().split(/\s+/).filter(Boolean);
  return tokens.length > 0 && tokens.every((token) => SAFE_AUTOCOMPLETE_TOKENS.has(token))
    ? tokens.join(" ")
    : null;
}

// Structural hostname validity only — no content screen. A host that fails this
// is malformed, not sensitive.
function safeHostnameV2(value: string): boolean {
  const hostname = value.toLowerCase();
  if (hostname.length === 0 || hostname.length > 253) return false;
  return hostname.split(".").every((label) => /^[a-z0-9](?:[a-z0-9-]{0,61}[a-z0-9])?$/.test(label));
}

export function safeOriginV2(value: string | null | undefined): string | null {
  if (typeof value !== "string") return null;
  try {
    const parsed = new URL(value);
    if (
      (parsed.protocol !== "https:" && parsed.protocol !== "http:") ||
      parsed.username.length > 0 ||
      parsed.password.length > 0 ||
      !safeHostnameV2(parsed.hostname)
    ) {
      return null;
    }
    return parsed.origin;
  } catch {
    return null;
  }
}

// Audit-trail sealing: the operator's structured stderr trail must never carry
// a raw URL or host while compact-v2 is sealing an observation. These two are
// the audit-side counterpart of safeOriginV2, and live here with it so both the
// lifecycle transaction and the observe/act surface can reach them.
export function compactV2AuditUrl(rawUrl: string): string {
  return safeOriginV2(rawUrl) ?? "<sealed-origin>";
}

export function compactV2AuditHost(rawHost: string): string {
  const origin = safeOriginV2(rawHost.includes("://") ? rawHost : `https://${rawHost}`);
  if (origin === null) return "<sealed-host>";
  return new URL(origin).host;
}

export function compactV2AuditValue(key: string, value: unknown): unknown {
  if ((key === "url" || key === "service_url") && typeof value === "string") {
    return compactV2AuditUrl(value);
  }
  if (
    (key === "host" || key === "url_host" || key === "frame_origin" || key === "recipe_domain") &&
    typeof value === "string"
  ) {
    return compactV2AuditHost(value);
  }
  if (key === "allowed_hosts" && Array.isArray(value)) {
    return value.map((host) =>
      typeof host === "string" ? compactV2AuditHost(host) : "<sealed-host>",
    );
  }
  if (typeof value === "string") return recordableTokenV2(value) ?? "<sealed>";
  if (Array.isArray(value)) return value.map((item) => compactV2AuditValue("", item));
  if (value !== null && typeof value === "object") {
    return Object.fromEntries(
      Object.entries(value).map(([nestedKey, nestedValue]) => [
        nestedKey,
        compactV2AuditValue(nestedKey, nestedValue),
      ]),
    );
  }
  return value;
}

export function sealRetainedInteractiveElementsV2(
  elements: readonly InteractiveElement[],
  selectorFor: (element: InteractiveElement) => string = () => "",
): InteractiveElement[] {
  // The retained inventory is what the recorded action trace reads its
  // dom_hint / accessible_name from, so it is screened for RECORDABILITY, not
  // by the payment-only observation policy. What the agent SEES is built from
  // freshly extracted elements through safeDescriptionV2.
  const description = (value: string | null | undefined): string | null =>
    recordableTokenV2(value) ?? null;
  const finiteToken = (
    value: string | null | undefined,
    allowed: ReadonlySet<string>,
  ): string | null => {
    const normalized = value?.toLowerCase();
    return normalized !== undefined && allowed.has(normalized) ? normalized : null;
  };
  const tags = new Set([
    "a",
    "button",
    "details",
    "input",
    "label",
    "option",
    "select",
    "summary",
    "textarea",
  ]);
  const types = new Set([
    "button",
    "checkbox",
    "date",
    "email",
    "file",
    "hidden",
    "image",
    "month",
    "number",
    "password",
    "radio",
    "reset",
    "search",
    "submit",
    "tel",
    "text",
    "time",
    "url",
    "week",
  ]);
  const roles = new Set([
    "button",
    "checkbox",
    "combobox",
    "link",
    "listbox",
    "menuitem",
    "option",
    "radio",
    "searchbox",
    "switch",
    "tab",
    "textbox",
  ]);
  return elements.map((element) => ({
    index: element.index,
    tag: finiteToken(element.tag, tags) ?? "unknown",
    type: finiteToken(element.type, types),
    id: description(element.id),
    name: description(element.name),
    placeholder: description(element.placeholder),
    ariaLabel: description(element.ariaLabel),
    role: finiteToken(element.role, roles),
    labelText: description(element.labelText),
    visibleText: description(element.visibleText),
    selector: selectorFor(element),
    visible: element.visible === true,
    inViewport: element.inViewport === true,
    inConsentWidget: element.inConsentWidget === true,
    href: null,
    iconLabel: description(element.iconLabel),
    title: description(element.title),
    testId: description(element.testId),
    autocomplete: safeAutocompleteV2(element.autocomplete),
    dataRole: null,
    landmark:
      typeof element.landmark === "string" &&
      /^(?:header|main|footer|nav|aside|article|section)$/.test(element.landmark)
        ? element.landmark
        : null,
    value: null,
    checked: element.checked ?? null,
    disabled: element.disabled ?? null,
    required: element.required ?? null,
    selectOptions: null,
    selectedOptionText: null,
    interactedThisRun: element.interactedThisRun === true,
    screenPath: null,
    container: null,
    containerId:
      typeof element.containerId === "number" &&
      Number.isSafeInteger(element.containerId) &&
      element.containerId > 0
        ? element.containerId
        : null,
    formId:
      typeof element.formId === "number" &&
      Number.isSafeInteger(element.formId) &&
      element.formId > 0
        ? element.formId
        : null,
    topmost: element.topmost ?? null,
    occludedBy: null,
    cardRadioGroup:
      element.cardRadioGroup !== null &&
      element.cardRadioGroup !== undefined &&
      Number.isSafeInteger(element.cardRadioGroup.id) &&
      Number.isSafeInteger(element.cardRadioGroup.position) &&
      Number.isSafeInteger(element.cardRadioGroup.total)
        ? {
            id: element.cardRadioGroup.id,
            position: element.cardRadioGroup.position,
            total: element.cardRadioGroup.total,
          }
        : null,
    frameOrigin: safeOriginV2(element.frameOrigin),
    frameUrl: null,
    framePath:
      typeof element.framePath === "string" && /^\d+(?:\/\d+)*$/.test(element.framePath)
        ? element.framePath
        : null,
    frameOpaque: element.frameOpaque === true,
  }));
}

export function safePageSemanticsV2(source: ObservationSemanticSourceV2): SafePageSemanticsV2 {
  const title = safeDescriptionV2(source.title);
  const headings = source.headings
    .map(safeDescriptionV2)
    .filter((value): value is string => value !== undefined)
    .filter((value, index, all) => all.indexOf(value) === index)
    .slice(0, 1);
  return {
    ...(title === undefined ? {} : { title }),
    ...(headings.length === 0 ? {} : { headings }),
  };
}

const BLOCKER_TEXT_MAX_CHARS = 160;
const BLOCKER_MAX_ITEMS = 3;
const CHALLENGE_SIGNAL_RE =
  /\b(?:captcha|turnstile|verification challenge|security challenge|security verification|verify (?:that )?you are human|human verification|not a robot)\b/i;
const CHALLENGE_MARKER_RE = /(?:captcha|turnstile|challenges?\.cloudflare\.com|cf[-_]challenge)/i;
const VALIDATION_SIGNAL_RE =
  /\b(?:error|failed|invalid|required|incorrect|missing|must|cannot|can't|couldn't|not valid|not found|please (?:complete|enter|select|choose|provide)|try again)\b/i;

function nodeTagV2(node: BrowserUseNode): string {
  return node.nodeType === 1 ? node.nodeName.toLowerCase() : "";
}

function axBooleanV2(node: BrowserUseNode, name: string): boolean {
  return node.axProperties.some((property) => property.name === name && property.value === true);
}

function boundedBlockerTextV2(value: string | null | undefined): string | undefined {
  if (value === null || value === undefined) return undefined;
  const normalized = value.normalize("NFKC").replace(/\s+/g, " ").trim();
  if (normalized.length === 0) return undefined;
  const characters = Array.from(normalized);
  return characters.length <= BLOCKER_TEXT_MAX_CHARS
    ? normalized
    : `${characters.slice(0, BLOCKER_TEXT_MAX_CHARS - 1).join("")}…`;
}

function blockerTextV2(node: BrowserUseNode): string | undefined {
  const candidates = [
    node.attributes["aria-label"],
    node.attributes.ax_name,
    node.attributes.title,
    browserUseBoundedContextText(node, BLOCKER_TEXT_MAX_CHARS),
    node.contentDocument === null
      ? null
      : browserUseBoundedContextText(node.contentDocument, BLOCKER_TEXT_MAX_CHARS),
  ];
  return candidates
    .map((candidate) => boundedBlockerTextV2(candidate))
    .find((candidate) => candidate !== undefined);
}

function blockerControlV2(node: BrowserUseNode): boolean {
  const tag = nodeTagV2(node);
  const role = (node.attributes.role ?? node.axRole ?? "").toLowerCase();
  const type = (node.attributes.type ?? "").toLowerCase();
  return (
    role === "checkbox" ||
    role === "button" ||
    tag === "button" ||
    (tag === "input" && ["button", "checkbox", "submit"].includes(type))
  );
}

function descendantsV2(node: BrowserUseNode): BrowserUseNode[] {
  return [...node.children, ...(node.contentDocument === null ? [] : [node.contentDocument])];
}

/**
 * Extract only task-blocking semantics from the canonical capture already used
 * by the full DOM serializer. This is deliberately structural: explicit
 * alert/invalid relationships and challenge-labelled boundaries qualify;
 * ordinary page prose does not.
 */
export function safeBlockersV2(
  root: BrowserUseNode,
  refForNode: (node: BrowserUseNode) => string | undefined = () => undefined,
): SafeBlockerV2[] {
  const nodes: BrowserUseNode[] = [];
  const parentFor = new Map<BrowserUseNode, BrowserUseNode>();
  const visibleFor = new Map<BrowserUseNode, boolean>();
  const scopeFor = new Map<BrowserUseNode, BrowserUseNode>();
  const idsByScope = new Map<BrowserUseNode, Map<string, BrowserUseNode>>();
  const visit = (
    node: BrowserUseNode,
    enclosingScope: BrowserUseNode,
    parent: BrowserUseNode | undefined,
    enclosingFrameVisible: boolean,
  ): void => {
    const scope = [9, 11].includes(node.nodeType) ? node : enclosingScope;
    const visible =
      enclosingFrameVisible && ([9, 11].includes(node.nodeType) ? true : node.visible);
    nodes.push(node);
    if (parent !== undefined) parentFor.set(node, parent);
    visibleFor.set(node, visible);
    scopeFor.set(node, scope);
    let ids = idsByScope.get(scope);
    if (ids === undefined) {
      ids = new Map();
      idsByScope.set(scope, ids);
    }
    const id = node.attributes.id?.trim();
    if (id) ids.set(id, node);
    const descendantsVisible =
      enclosingFrameVisible && (!["iframe", "frame"].includes(nodeTagV2(node)) || visible);
    descendantsV2(node).forEach((child) => visit(child, scope, node, descendantsVisible));
  };
  visit(root, root, undefined, true);

  const challengeCandidates = nodes.filter((node) => {
    if (visibleFor.get(node) !== true) return false;
    const tag = nodeTagV2(node);
    const identity = [
      tag,
      node.attributes.id,
      node.attributes.class,
      node.attributes.title,
      node.attributes["aria-label"],
      node.attributes.ax_name,
      node.attributes.src,
    ]
      .filter((value): value is string => typeof value === "string")
      .join(" ");
    if (CHALLENGE_MARKER_RE.test(identity)) return true;
    if (node.nodeType === 3) {
      const text = blockerTextV2(node) ?? "";
      return (
        CHALLENGE_SIGNAL_RE.test(text) &&
        (VALIDATION_SIGNAL_RE.test(text) || /\bperforming security verification\b/i.test(text))
      );
    }
    if (
      !["iframe", "frame", "label"].includes(tag) &&
      (node.attributes.role ?? node.axRole ?? "").toLowerCase() !== "alert" &&
      !blockerControlV2(node)
    ) {
      return false;
    }
    return CHALLENGE_SIGNAL_RE.test(blockerTextV2(node) ?? "");
  });
  const challengeCandidateSet = new Set(challengeCandidates);
  const challengeRoots = challengeCandidates.filter((node) => {
    let parent = parentFor.get(node);
    while (parent !== undefined) {
      if (challengeCandidateSet.has(parent)) return false;
      parent = parentFor.get(parent);
    }
    return true;
  });

  const blockers: SafeBlockerV2[] = [];
  for (const challengeRoot of challengeRoots) {
    if (blockers.length >= BLOCKER_MAX_ITEMS) break;
    const boundaryNodes: BrowserUseNode[] = [];
    const controls = new Set<BrowserUseNode>();
    const collectControls = (node: BrowserUseNode): void => {
      if (visibleFor.get(node) === true) {
        boundaryNodes.push(node);
        if (blockerControlV2(node)) controls.add(node);
      }
      descendantsV2(node).forEach(collectControls);
    };
    collectControls(challengeRoot);
    const namedChallengeControls = [...controls].filter((node) =>
      CHALLENGE_SIGNAL_RE.test(blockerTextV2(node) ?? ""),
    );
    const checkboxControls = [...controls].filter((node) => {
      const role = (node.attributes.role ?? node.axRole ?? "").toLowerCase();
      return (
        role === "checkbox" || (nodeTagV2(node) === "input" && node.attributes.type === "checkbox")
      );
    });
    const challengeControls =
      checkboxControls.length > 0 ? checkboxControls : namedChallengeControls;
    const grounded = challengeControls.find((node) => refForNode(node) !== undefined);
    const focusControl =
      grounded ??
      challengeControls.find((node) => axBooleanV2(node, "focused")) ??
      challengeControls.find((node) => axBooleanV2(node, "focusable"));
    const focused = focusControl !== undefined && axBooleanV2(focusControl, "focused");
    const focusable = focusControl !== undefined && axBooleanV2(focusControl, "focusable");
    const challengeTexts = boundaryNodes
      .map(blockerTextV2)
      .filter((value): value is string => value !== undefined && CHALLENGE_SIGNAL_RE.test(value));
    const labelText = boundaryNodes
      .filter((node) => nodeTagV2(node) === "label")
      .map(blockerTextV2)
      .find((value) => value !== undefined && CHALLENGE_SIGNAL_RE.test(value));
    const message = challengeTexts.find((value) => VALIDATION_SIGNAL_RE.test(value));
    const controlText =
      (focusControl === undefined ? undefined : blockerTextV2(focusControl)) ??
      challengeControls.map(blockerTextV2).find((value) => value !== undefined);
    const text =
      message ?? controlText ?? labelText ?? challengeTexts[0] ?? "Verification challenge";
    const ref = grounded === undefined ? undefined : refForNode(grounded);
    blockers.push({
      kind: "challenge",
      text,
      ...(ref === undefined ? { target: "unavailable" as const } : { ref }),
      ...(focused
        ? { focus: "focused" as const, keyboard: "space" as const }
        : focusable
          ? { focus: "focusable" as const, keyboard: "tab_space" as const }
          : {}),
    });
  }

  const validationNodes = new Set<BrowserUseNode>();
  for (const node of nodes) {
    const role = (node.attributes.role ?? node.axRole ?? "").toLowerCase();
    const validationMarker = [node.attributes.id, node.attributes.class]
      .filter((value): value is string => typeof value === "string")
      .some((value) => /(?:^|[-_:])(error|invalid|validation|feedback)(?:$|[-_:])/i.test(value));
    if (
      visibleFor.get(node) === true &&
      (["alert", "alertdialog", "status"].includes(role) ||
        node.attributes["aria-live"] === "assertive" ||
        validationMarker)
    ) {
      const text = blockerTextV2(node);
      if (
        text !== undefined &&
        VALIDATION_SIGNAL_RE.test(text) &&
        !CHALLENGE_SIGNAL_RE.test(text)
      ) {
        validationNodes.add(node);
      }
    }
    const invalid = [node.attributes["aria-invalid"], node.attributes.invalid].some(
      (value) => value?.toLowerCase() === "true",
    );
    if (!invalid || visibleFor.get(node) !== true) continue;
    const ids = idsByScope.get(scopeFor.get(node)!);
    for (const [relation, explicitError] of [
      [node.attributes["aria-errormessage"], true],
      [node.attributes["aria-describedby"], false],
    ] as const) {
      for (const id of relation?.trim().split(/\s+/) ?? []) {
        const related = ids?.get(id);
        const relatedText = related === undefined ? undefined : blockerTextV2(related);
        if (
          related !== undefined &&
          visibleFor.get(related) === true &&
          relatedText !== undefined &&
          (explicitError || VALIDATION_SIGNAL_RE.test(relatedText))
        ) {
          validationNodes.add(related);
        }
      }
    }
  }
  for (const node of validationNodes) {
    if (blockers.length >= BLOCKER_MAX_ITEMS) break;
    const text = blockerTextV2(node);
    if (text === undefined || blockers.some((blocker) => blocker.text === text)) continue;
    blockers.push({ kind: "validation", text });
  }
  return blockers;
}

const INTENTS: ReadonlyArray<[SafeIntentV2, RegExp]> = [
  ["add_to_cart", /add\s+(?:to\s+)?(?:cart|bag|basket)/i],
  ["view_cart", /view\s+(?:cart|bag|basket)/i],
  ["destructive", /\b(?:delete|remove|erase|destroy)\b/i],
  ["checkout", /^(?:(?:go|proceed|continue)(?:\s+to)?\s+)?(?:secure\s+)?checkout(?:\s+now)?$/i],
  ["payment", /\b(?:pay(?:ment)?|card)\b/i],
  ["signup", /sign\s*up|create\s+(?:account|workspace)|register/i],
  ["login", /log\s*in|sign\s*in|continue\s+with/i],
  ["search", /search|find/i],
  ["close", /close|dismiss|cancel|no\s+thanks/i],
  ["next", /next/i],
  ["previous", /previous|back/i],
  ["submit", /submit|save|create|send/i],
  ["continue", /continue|proceed|start|accept|allow|keep|retain/i],
];

const BUTTON_INPUT_TYPES = new Set(["button", "submit", "reset", "image"]);

function isButtonInput(el: InteractiveElement): boolean {
  return el.tag === "input" && BUTTON_INPUT_TYPES.has((el.type ?? "").toLowerCase());
}

function controlNamingTexts(el: InteractiveElement): Array<string | null | undefined> {
  return [
    el.visibleText,
    el.labelText,
    el.ariaLabel,
    el.iconLabel,
    el.title,
    el.placeholder,
    isButtonInput(el) ? el.value : undefined,
  ];
}

function controlLabelNamingTexts(el: InteractiveElement): Array<string | null | undefined> {
  const role = roleOf(el);
  const names = el.compactNames;
  if (names) {
    const accessibleName = normalizeDescriptionV2(names.accessibleName);
    const visibleText = normalizeDescriptionV2(names.visibleText);
    const iconLabel = normalizeDescriptionV2(names.iconLabel);
    const aggregateIconName =
      visibleText !== undefined &&
      iconLabel !== undefined &&
      accessibleName === `${iconLabel} ${visibleText}`;
    return [
      aggregateIconName ? undefined : names.accessibleName,
      names.ariaLabel,
      names.labelledByText,
      names.labelText,
      (el.type ?? "").toLowerCase() === "image" ? names.alt : undefined,
      names.visibleText,
      isButtonInput(el) ? names.value : undefined,
      names.iconLabel,
      names.title,
      role === "textbox" ? names.placeholder : undefined,
      role === "textbox" ? names.name : undefined,
    ];
  }
  return [
    el.ariaLabel,
    el.labelText,
    el.visibleText,
    isButtonInput(el) ? el.value : undefined,
    el.iconLabel,
    el.title,
    role === "textbox" ? el.placeholder : undefined,
    role === "textbox" ? el.name : undefined,
  ];
}

function candidateTexts(el: InteractiveElement): string[] {
  return [
    el.visibleText,
    el.labelText,
    el.ariaLabel,
    el.iconLabel,
    el.title,
    el.placeholder,
    el.name,
    el.id,
    ...(isButtonInput(el) ? [el.value] : []),
  ]
    .filter((part): part is string => typeof part === "string")
    .map((part) => part.replace(/[-_]+/g, " ").replace(/\s+/g, " ").trim())
    .filter(Boolean);
}

function candidateText(el: InteractiveElement): string {
  return candidateTexts(el).join(" ");
}

function controlDescription(el: InteractiveElement, role: SafeRoleV2): string {
  // Prefer authored accessibility names over descendant text. Navigation
  // toggles and data-row controls often contain an entire menu/card subtree;
  // choosing textContent first turned their concise aria/label name into a
  // mashed-together alias. Native button values are names, while field values
  // and ids remain excluded. Textbox placeholder/name are useful only after
  // the genuine accessibility and visible-name sources have been exhausted.
  const chosen = controlLabelNamingTexts(el)
    .map((candidate) => normalizeDescriptionV2(candidate))
    .find((candidate) => candidate !== undefined);
  if (chosen !== undefined) {
    // Add the page's region context to otherwise opaque labels (such as @as15169).
    const context = regionContextV2(
      el.compactNames ? el.compactNames.container : el.container,
      chosen,
    );
    const description = context === undefined ? chosen : `${chosen} ${context}`;
    if (controlLabelV2(description) !== undefined) return description;
  }
  // Every actionable row still needs a human-usable alias. The nearest
  // semantic region is the best available immediate context; a genuinely
  // anonymous control falls back to its role rather than becoming a bare
  // [ref, role] tuple. This is descriptive only and does not alter identity.
  const context = namedContainerContextV2(
    el.compactNames ? el.compactNames.container : el.container,
  );
  return context === undefined ? `${role} ${el.index + 1}` : `${context} ${role}`;
}

/** A description is "uninformative" when it carries no 3+-letter word run: ids, short codes, hex fragments. */
function isUninformativeDescriptionV2(description: string): boolean {
  return (
    !/[a-zA-Z]{3,}/.test(description) &&
    !Array.from(description).some(
      (character) => character.charCodeAt(0) > 0x7f && /\p{L}/u.test(character),
    )
  );
}

function regionContextV2(container: string | null | undefined, chosen: string): string | undefined {
  if (container === null || container === undefined) return undefined;
  if (!isUninformativeDescriptionV2(chosen)) return undefined;
  const context = namedContainerContextV2(container);
  if (context === undefined) return undefined;
  return context.slice(0, 24).replace(/-+$/, "") || undefined;
}

function namedContainerContextV2(container: string | null | undefined): string | undefined {
  if (container === null || container === undefined) return undefined;
  const separator = container.indexOf(":");
  const kind = separator < 0 ? undefined : container.slice(0, separator).toLowerCase();
  const raw = separator < 0 ? container : container.slice(separator + 1);
  const context = safeDescriptionV2(raw.replace(/[-_]+/g, " "));
  return context === undefined || context.toLowerCase() === kind ? undefined : context;
}

function privateQueryTokenV2(value: string): string | null {
  const normalized = value.normalize("NFKC").trim().toLowerCase();
  if (
    normalized.length < 1 ||
    normalized.length > 48 ||
    !/^[\p{L}\p{M}\p{N}]{1,48}$/u.test(normalized)
  ) {
    return null;
  }
  return normalized;
}

function privateQueryTermsV2(value: string): string[] | null {
  const normalized = value.normalize("NFKC").trim().toLowerCase();
  if (normalized.length < 1 || normalized.length > 96) return null;
  const rawTerms = normalized.match(/[\p{L}\p{M}\p{N}]{1,48}/gu);
  if (rawTerms === null || rawTerms.length === 0 || rawTerms.length > 6) return null;
  const separators = normalized.replace(/[\p{L}\p{M}\p{N}]{1,48}/gu, "");
  if (!/^[\s&'’+,.!?():/_|-]*$/u.test(separators)) return null;
  const terms = rawTerms.map(privateQueryTokenV2);
  return terms.every((term): term is string => term !== null) ? [...new Set(terms)] : null;
}

export function controlQueryMatchV2(
  el: InteractiveElement,
  query: string,
): { rank: number; provenance: SafeQueryMatchV2 } | null {
  const needles = privateQueryTermsV2(query);
  if (needles === null) return null;
  const phrase = (value: string | null | undefined): string | null => {
    if (!value) return null;
    const terms = privateQueryTermsV2(value);
    return terms === null ? null : terms.join(" ");
  };
  const queryPhrase = needles.join(" ");
  const names = el.compactNames;
  const accessibleNames = names
    ? [
        names.accessibleName,
        names.ariaLabel,
        names.labelledByText,
        ["button", "input", "select", "textarea"].includes(el.tag) ? names.labelText : null,
      ]
    : [el.ariaLabel, el.labelText];
  if (accessibleNames.some((candidate) => phrase(candidate) === queryPhrase)) {
    return { rank: 0, provenance: "name" };
  }
  const role = roleOf(el);
  const roleWords =
    role === "select" ? ["select", "dropdown", "combobox"] : role === null ? [] : [role];
  if (needles.length === 1 && roleWords.includes(needles[0]!)) {
    return { rank: 1, provenance: "role" };
  }
  // AND-match every term against this control's own name/text/DOM metadata.
  // Ancestor/page text is excluded, so a page root or sidebar cannot lend its
  // name to every descendant action.
  const localCandidates: Array<string | null | undefined> = [
    ...controlNamingTexts(el),
    el.name,
    el.id,
    ...roleWords,
  ];
  const combined = new Set<string>();
  for (const candidate of localCandidates) {
    if (typeof candidate !== "string" || candidate.length === 0) continue;
    const tokens = candidate.normalize("NFKC").match(/[\p{L}\p{M}\p{N}]{1,48}/gu);
    if (tokens === null) continue;
    for (const token of tokens) {
      const safe = privateQueryTokenV2(token);
      if (safe !== null) combined.add(safe);
    }
  }
  if (needles.every((needle) => combined.has(needle))) {
    return { rank: 2, provenance: "text" };
  }
  const container = names?.container ?? el.container;
  const separator = container?.indexOf(":") ?? -1;
  const kind = separator < 0 ? "" : container!.slice(0, separator).toLowerCase();
  // Explicit form/dialog ownership is local enough to be useful. Broad main,
  // navigation and section copy is not query authority.
  if (["form", "fieldset", "dialog"].includes(kind)) {
    const contextTerms = privateQueryTermsV2(container!.slice(separator + 1));
    if (contextTerms !== null) {
      const context = new Set(contextTerms);
      if (needles.every((needle) => context.has(needle))) {
        return { rank: 3, provenance: "context" };
      }
    }
  }
  return null;
}

export function controlMatchesPrivateQueryV2(el: InteractiveElement, query: string): boolean {
  return controlQueryMatchV2(el, query) !== null;
}

function roleOf(el: InteractiveElement): SafeRoleV2 | null {
  const role = (el.role ?? "").toLowerCase();
  const type = (el.type ?? "").toLowerCase();
  if (type === "file") return "file";
  if (isButtonInput(el)) return "button";
  if (type === "checkbox" || role === "checkbox") return "checkbox";
  if (type === "radio" || role === "radio") return "radio";
  if (el.tag === "select" || role === "combobox" || role === "listbox") return "select";
  if (el.tag === "input" || el.tag === "textarea" || role === "textbox") return "textbox";
  if (el.tag === "a" || role === "link") return "link";
  if (role === "tab") return "tab";
  if (role === "menuitem" || role === "option") return "menuitem";
  if (el.tag === "button" || role === "button") {
    return "button";
  }
  return role || null;
}

function stateOf(el: InteractiveElement): string | undefined {
  // A compact code-owned bitset: c=checked, u=unchecked, d=disabled,
  // r=required.  It is deliberately not a page-provided string.
  let state = "";
  if (el.checked === true) state += "c";
  else if (el.checked === false) state += "u";
  if (el.disabled === true) state += "d";
  if (el.required === true) state += "r";
  return state || undefined;
}

function intentOf(el: InteractiveElement): SafeIntentV2 | undefined {
  const texts = candidateTexts(el);
  return INTENTS.find(([, expression]) => texts.some((text) => expression.test(text)))?.[0];
}

function hasExplicitPaymentFieldSignal(el: InteractiveElement): boolean {
  const autocomplete = (el.autocomplete ?? "").toLowerCase();
  const text = candidateText(el).toLowerCase();
  return (
    autocomplete
      .trim()
      .split(/\s+/)
      .some((token) => token.startsWith("cc-")) ||
    /\b(?:cvc|cvv|csc|card verification(?: (?:value|number))?|card security code)\b/.test(text) ||
    /\b(?:card number|payment card|credit card|debit card)\b/.test(text)
  );
}

function fieldOf(el: InteractiveElement, paymentContext = false): SafeFieldV2 | undefined {
  const autocomplete = (el.autocomplete ?? "").toLowerCase();
  const autocompleteTokens = new Set(autocomplete.trim().split(/\s+/).filter(Boolean));
  const hasAutocomplete = (...tokens: string[]): boolean =>
    tokens.some((token) => autocompleteTokens.has(token));
  const type = (el.type ?? "").toLowerCase();
  const text = candidateText(el).toLowerCase();
  if (
    hasExplicitPaymentFieldSignal(el) ||
    (paymentContext && /\b(?:security code|cvn|cid)\b/.test(text))
  ) {
    return "payment";
  }
  if (type === "password" || hasAutocomplete("current-password", "new-password")) {
    return "password";
  }
  if (type === "email" || hasAutocomplete("email") || /\be-?mail\b/.test(text)) return "email";
  if (
    type === "tel" ||
    [...autocompleteTokens].some((token) => token === "tel" || token.startsWith("tel-")) ||
    /\b(phone|mobile|telephone)\b/.test(text)
  )
    return "phone";
  if (type === "search" || /\bsearch\b/.test(text)) return "search";
  if (hasAutocomplete("username") || /\b(user ?name|handle)\b/.test(text)) return "username";
  if (/\b(card|payment|cc-)/.test(`${autocomplete} ${text}`)) return "payment";
  if (hasAutocomplete("address-level2") || /\b(city|town)\b/.test(text)) return "city";
  if (hasAutocomplete("address-level1") || /\b(state|province|region)\b/.test(text))
    return "region";
  if (hasAutocomplete("postal-code") || /\b(zip|postal)\b/.test(text)) return "postal";
  if (hasAutocomplete("country", "country-name") || /\bcountry\b/.test(text)) return "country";
  // `address-line2` is the optional apartment/suite field in the HTML
  // autocomplete vocabulary. Shopify renders it directly below a required
  // Places-backed `address-line1` combobox. Treating both as `address` makes
  // the compact action map advertise two interchangeable street fields, and a
  // caller can put the delivery address in the apartment field instead. Keep
  // `address` reserved for the required street-address / line-1 control; the
  // optional secondary line is intentionally not a checkout fill target.
  if (
    hasAutocomplete("address-line2", "address-line3") ||
    /\b(?:apartment|apt\.?|suite|unit|floor|building)\b/.test(text) ||
    /\boptional\b/.test(text)
  )
    return undefined;
  if (hasAutocomplete("street-address", "address-line1") || /\b(address|street)\b/.test(text))
    return "address";
  if (
    type === "date" ||
    [...autocompleteTokens].some((token) => token.startsWith("bday")) ||
    /\bdate\b/.test(text)
  )
    return "date";
  if (/\b(quantity|qty)\b/.test(text)) return "quantity";
  if (/\b(promo|coupon|discount)\b/.test(text)) return "promo";
  if (
    [...autocompleteTokens].some((token) => token === "name" || token.endsWith("-name")) ||
    /\b(full )?name\b/.test(text)
  )
    return "name";
  return undefined;
}

/** A code-owned page-stage enum; it never forwards the URL or page copy. */
export function safeStageV2(url: string, elements: readonly InteractiveElement[]): SafeStageV2 {
  let pathname = "";
  try {
    pathname = decodeURIComponent(new URL(url).pathname).toLowerCase();
  } catch {}
  if (
    /(?:^|\/)(?:success|complete|thank-you|thank_you|finished|done)(?:\.(?:php|html?))?(?:\/|$)/.test(
      pathname,
    )
  ) {
    return "complete";
  }
  const actionableElements = elements.filter(
    (element) => element.visible === true && element.topmost !== false,
  );
  const routeStage = checkoutStageFromUrlV2(url);
  const paymentContext =
    routeStage !== null ||
    actionableElements.some((element) => hasExplicitPaymentFieldSignal(element));
  const checkoutFields = new Set<SafeFieldV2>([
    "address",
    "city",
    "region",
    "postal",
    "country",
    "payment",
  ]);
  const hasCheckoutField = actionableElements.some((el) => {
    const role = roleOf(el);
    const field = fieldOf(el, paymentContext);
    return (
      (role === "textbox" || role === "select") && field !== undefined && checkoutFields.has(field)
    );
  });
  const authFields = actionableElements.filter((el) => {
    const role = roleOf(el);
    if (role !== "textbox" && role !== "select") return false;
    const field = fieldOf(el, paymentContext);
    return field === "email" || field === "username" || field === "password";
  });
  const hasPasswordField = authFields.some((el) => fieldOf(el, paymentContext) === "password");
  const authRoute =
    /(?:^|\/)(?:login|log-in|signin|sign-in|signup|sign-up|register|auth)(?:\.(?:php|html?))?(?:\/|$)/.test(
      pathname,
    );
  const hasScopedAuthForm = actionableElements.some((el) => {
    if (roleOf(el) !== "button" || (intentOf(el) !== "login" && intentOf(el) !== "signup")) {
      return false;
    }
    const ownerId = el.formId ?? el.containerId;
    const framePath = el.framePath ?? null;
    return (
      ownerId !== undefined &&
      ownerId !== null &&
      authFields.some(
        (field) =>
          (field.formId ?? field.containerId) === ownerId &&
          (field.framePath ?? null) === framePath,
      )
    );
  });
  // A password editor on an authenticated settings page is a form, not proof
  // that the whole document is a login surface. Require a local login/signup
  // submit owner, or an auth route plus an auth field.
  if (hasScopedAuthForm || (authRoute && (hasPasswordField || authFields.length > 0)))
    return "auth";
  if (routeStage !== null) return routeStage;
  const hasPaymentField = actionableElements.some((el) => {
    const role = roleOf(el);
    return (role === "textbox" || role === "select") && fieldOf(el, paymentContext) === "payment";
  });
  const hasCheckoutAction = actionableElements.some(
    (el) => roleOf(el) === "button" && intentOf(el) === "checkout",
  );
  if (hasPaymentField || (hasCheckoutAction && hasCheckoutField)) return "checkout";
  if (actionableElements.some((el) => intentOf(el) === "add_to_cart")) return "browse";
  if (actionableElements.some((el) => roleOf(el) === "textbox" || roleOf(el) === "select"))
    return "form";
  return "browse";
}

export function checkoutStageFromUrlV2(url: string): "cart" | "checkout" | null {
  let pathname = "";
  try {
    pathname = decodeURIComponent(new URL(url).pathname).toLowerCase();
  } catch {
    return null;
  }
  if (
    /(?:^|\/)(?:checkout|secure[-_]?checkout|payment|order[-_]?review|order\/review)(?:\.(?:php|html?))?(?:\/|$)/i.test(
      pathname,
    )
  ) {
    return "checkout";
  }
  if (
    /(?:^|\/)(?:cart|shopping[-_]?cart|view[-_]?cart|basket|bag)(?:\.(?:php|html?))?(?:\/|$)/i.test(
      pathname,
    )
  ) {
    return "cart";
  }
  return null;
}

function frameOf(el: InteractiveElement, pageOrigin: string): SafeControlV2["frame"] {
  if (el.frameOrigin === null || el.frameOrigin === undefined) return "main";
  return el.frameOrigin === pageOrigin ? "same_origin" : "cross_origin";
}

/**
 * Deterministically disambiguate duplicate labels within one snapshot. The
 * /dashboard/token dogfood returned two distinct rows both labelled
 * `@curl-example` with nothing to tell them apart — a correct pick was a coin
 * flip. The first occurrence keeps the plain label; the second and later
 * occurrences get a stable ordinal suffix (`@curl-example-2`, `-3`, …)
 * following the map's own row order, so the same page always yields the same
 * numbering. A suffix that would collide with an existing label (the page
 * itself rendering "curl example 2" alongside two "curl example" rows) is
 * skipped, so disambiguation never mints a new ambiguity.
 */
export function disambiguateDuplicateLabelsV2(
  labels: readonly (string | undefined)[],
): Array<string | undefined> {
  const occurrences = new Map<string, number>();
  for (const label of labels) {
    if (label === undefined) continue;
    occurrences.set(label, (occurrences.get(label) ?? 0) + 1);
  }
  const assigned = new Set<string>();
  for (const label of labels) if (label !== undefined) assigned.add(label);
  const seen = new Map<string, number>();
  return labels.map((label) => {
    if (label === undefined) return undefined;
    const occurrence = (seen.get(label) ?? 0) + 1;
    seen.set(label, occurrence);
    if (occurrence === 1) return label;
    let suffix = occurrence;
    let candidate = labelWithOrdinalV2(label, suffix);
    while (assigned.has(candidate)) {
      suffix += 1;
      candidate = labelWithOrdinalV2(label, suffix);
    }
    assigned.add(candidate);
    return candidate;
  });
}

export function buildSafeControlsV2(args: {
  elements: readonly InteractiveElement[];
  legacyRefs: ReadonlyMap<InteractiveElement, string>;
  /** Durable per-element handles, minted by the session (document-scoped). */
  handles: ReadonlyMap<InteractiveElement, string>;
  pageOrigin: string;
  pageUrl?: string;
  canonical?: boolean;
  anchorLabel?: (ref: string, preferred: string | undefined) => string | undefined;
}): { rows: SafeControlV2[]; byRef: Map<string, string> } {
  const rows: Array<{
    ref: string;
    legacy: string;
    row: Omit<SafeControlV2, "ref">;
    priority: number;
  }> = [];
  const paymentContext =
    checkoutStageFromUrlV2(args.pageUrl ?? "") !== null ||
    args.elements.some((element) => hasExplicitPaymentFieldSignal(element));
  for (const el of args.elements) {
    if (el.visible !== true || (!args.canonical && el.topmost === false)) continue;
    const role = roleOf(el) ?? (args.canonical ? el.role || "generic" : null);
    const legacy = args.legacyRefs.get(el);
    const ref = args.handles.get(el);
    if (role === null || legacy === undefined || ref === undefined) continue;
    const state = stateOf(el);
    const action = intentOf(el);
    const field = fieldOf(el, paymentContext);
    const cardChoice = el.cardRadioGroup;
    // Native TypeScript port of browse-use's compact DOM formatting: the
    // already CDP-derived interactive inventory supplies each visible control's
    // descendant/accessibility name. This pass binds that name to its own live
    // element, so no cross-serializer tag/role fallback can swap labels.
    const label = controlLabelV2(controlDescription(el, role));
    const row: Omit<SafeControlV2, "ref"> = {
      role,
      visibility: el.inViewport ? "viewport" : "near",
      frame: frameOf(el, args.pageOrigin),
      ...(state === undefined ? {} : { state }),
      ...(action === undefined ? {} : { action }),
      ...(field === undefined ? {} : { field }),
      ...(label === undefined ? {} : { label }),
      ...(cardChoice === null || cardChoice === undefined
        ? {}
        : { choice: `${cardChoice.position}/${cardChoice.total}` }),
    };
    // A signup/login action is the useful first move on a landing page. Put it
    // ahead of unlabeled navigation chrome while preserving the existing
    // viewport and role ordering within each group.
    const actionPriority = action === "signup" ? -20 : action === "login" ? -10 : 0;
    rows.push({
      ref,
      legacy,
      row,
      priority: actionPriority + (el.inViewport ? 0 : 10) + (role === "button" ? 0 : 1),
    });
  }
  rows.sort((a, b) => a.priority - b.priority || a.legacy.localeCompare(b.legacy));
  // The legacy fallback disambiguates after final ordering. Compact-v2 supplies
  // anchorLabel instead, reserving each alias for its physical-node capability.
  const disambiguated = disambiguateDuplicateLabelsV2(rows.map(({ row }) => row.label));
  const byRef = new Map<string, string>();
  const safeRows = rows.map(({ ref, legacy, row }, position) => {
    const label = args.anchorLabel ? args.anchorLabel(ref, row.label) : disambiguated[position];
    byRef.set(ref, legacy);
    return { ref, ...row, ...(label === undefined ? {} : { label }) };
  });
  return { rows: safeRows, byRef };
}

export function encodeV2QueryPage(args: {
  sessionId: string;
  stage: SafeStageV2;
  /** The live page URL, path and query included — the agent needs to know where it is. */
  pageUrl?: string;
  semantics?: SafePageSemanticsV2;
  rows: readonly SafeControlV2[];
  cursorFor: (offset: number) => string;
  offset?: number;
  startMetadata?: {
    hint?: string;
    userEmail?: string;
    hintOverflow?: { remaining: number; next_cursor: string };
  };
}): { payload: Record<string, unknown>; nextOffset: number } {
  const offset = args.offset ?? 0;
  let fixed: Record<string, unknown> = {
    format: "browser-use-control-query",
    url: args.pageUrl ?? "",
    session_id: args.sessionId,
    stage: args.stage,
    ...(args.startMetadata?.hint === undefined ? {} : { hint: args.startMetadata.hint }),
    ...(args.startMetadata?.userEmail === undefined
      ? {}
      : { user_email: args.startMetadata.userEmail }),
    ...(args.startMetadata?.hintOverflow === undefined
      ? {}
      : { hint_overflow: args.startMetadata.hintOverflow }),
    ...(args.semantics === undefined || Object.keys(args.semantics).length === 0
      ? {}
      : { semantic: args.semantics }),
  };
  const pageWith = (
    table: readonly WireControlV2[],
    nextOffset: number,
  ): Record<string, unknown> => {
    const remaining = args.rows.length - nextOffset;
    return {
      ...fixed,
      safe_table: table,
      ...(remaining > 0
        ? { overflow: { remaining, next_cursor: args.cursorFor(nextOffset) } }
        : {}),
    };
  };
  if (offset < args.rows.length) {
    const probe = pageWith([wireControl(args.rows[offset]!)], offset + 1);
    if (!compactV2PayloadWithinBudget(probe)) {
      const degraded = compactV2DegradeMetadata(probe);
      if (degraded === null) throw new Error("compact-v2 budget metadata exceeded");
      const degradedFixed = { ...degraded };
      delete degradedFixed.safe_table;
      delete degradedFixed.overflow;
      fixed = degradedFixed;
    }
  }
  const visible: WireControlV2[] = [];
  // Every interactive control is a candidate for the default map: rows are
  // packed in priority order until the wire budget is actually reached, so a
  // below-the-fold primary CTA is never stranded behind an arbitrary row cap
  // (the live Xata failure). Overflow remains reachable through the in-MCP
  // query cursor, never a shell-readable snapshot file.
  let nextOffset = offset;
  for (let index = offset; index < args.rows.length; index += 1) {
    const candidate = wireControl(args.rows[index]!);
    if (!compactV2PayloadWithinBudget(pageWith([...visible, candidate], index + 1))) break;
    visible.push(candidate);
    nextOffset = index + 1;
  }
  if (visible.length === 0 && offset < args.rows.length) {
    // Budget-driven packing must never emit an empty page whose cursor points
    // back at the same offset. Force the first row in and let fixed metadata
    // degrade around it — on a real page this is unreachable.
    visible.push(wireControl(args.rows[offset]!));
    nextOffset = offset + 1;
  }
  let payload = pageWith(visible, nextOffset);
  if (!compactV2PayloadWithinBudget(payload)) {
    // Only hostile fixed metadata (a code-owned session id/cursor) lands here;
    // degrade the metadata before ever dropping an actionable row.
    const degraded = compactV2DegradeMetadata(payload);
    if (degraded === null) throw new Error("compact-v2 budget metadata exceeded");
    payload = degraded;
  }
  return { payload, nextOffset };
}
