import { Buffer } from "node:buffer";
import type { InteractiveElement } from "./browser.js";
import {
  findCredentialTokens,
  findOtpCredential,
  isStandaloneOtpCredential,
  looksLikeCredentialValue,
} from "./credential-shape.js";

export const OBSERVE_V2_MAX_WIRE_BYTES = 4_096;
export const OBSERVE_V2_MAX_TOKENS = 1_024;
const FIRST_PAGE_ROW_LIMIT = 4;

export function compactV2PayloadWithinBudget(payload: unknown): boolean {
  const bytes = Buffer.byteLength(JSON.stringify(payload), "utf8");
  return bytes <= OBSERVE_V2_MAX_WIRE_BYTES && bytes <= OBSERVE_V2_MAX_TOKENS;
}

export type SafeRoleV2 =
  | "button"
  | "link"
  | "textbox"
  | "select"
  | "checkbox"
  | "radio"
  | "tab"
  | "menuitem"
  | "file";
export type SafeIntentV2 =
  | "search"
  | "close"
  | "next"
  | "previous"
  | "submit"
  | "continue"
  | "login"
  | "signup"
  | "add_to_cart"
  | "view_cart"
  | "checkout"
  | "payment";
// These are semantic classes generated by TS, never page-provided labels. They
// make a small action map useful for forms while keeping values, merchant copy,
// live regions, and secrets on the private side of the seal.
export type SafeFieldV2 =
  | "email"
  | "password"
  | "username"
  | "name"
  | "phone"
  | "search"
  | "address"
  | "city"
  | "region"
  | "postal"
  | "country"
  | "date"
  | "quantity"
  | "promo"
  | "payment";
export type SafeStageV2 = "browse" | "auth" | "form" | "cart" | "checkout" | "complete";

export interface SafeControlV2 {
  ref: string;
  role: SafeRoleV2;
  state?: string;
  visibility: "viewport" | "near";
  action?: SafeIntentV2;
  field?: SafeFieldV2;
  /** Short, screened descriptive control label; never a field value. */
  name?: string;
  choice?: string;
  frame: "main" | "same_origin" | "cross_origin";
}

/** Raw DOM input is accepted only from title and visible heading elements. */
export interface ObservationSemanticSourceV2 {
  title: string;
  headings: readonly string[];
}

export interface SafePageSemanticsV2 {
  title?: string;
  headings?: string[];
}

export interface SafeObservationIndexV2 {
  generation: number;
  /** Internal HMAC page identity for the snapshot this index was minted from. */
  pageKey: string;
  stage: SafeStageV2;
  semantics: SafePageSemanticsV2;
  rows: SafeControlV2[];
  byRef: Map<string, string>;
  expiresAt: number;
}

/**
 * The only V2 state retained between observations.  These rows have already
 * crossed the allowlist seal: they contain generation-bound index refs and
 * code-owned enums, never DOM values or arbitrary page copy.
 */
export interface SafeObservationBaselineV2 {
  /** Internal HMAC page identity; never emitted or persisted outside the session. */
  pageKey: string;
  /** The generation encoded into every current short action index. */
  snapshotGeneration: number;
  stage: SafeStageV2;
  semantics: SafePageSemanticsV2;
  byRef: Map<string, SafeControlV2>;
}

/**
 * Semantic essentials are sticky across V2 deltas. A repeat observation only
 * needs to carry them when their already-sealed representation changed; the
 * consumer retains the prior title/heading just like it retains safe_table.
 */
export function equalSafePageSemanticsV2(
  left: SafePageSemanticsV2,
  right: SafePageSemanticsV2,
): boolean {
  return left.title === right.title && (left.headings?.[0] ?? "") === (right.headings?.[0] ?? "");
}

const COMPACT_V2_HANDLE_RE = /^@e:([0-9a-z]+)\.([0-9a-z]+)$/i;

/**
 * Resolve a compact index only when it is a canonical handle for the current
 * snapshot generation AND a member of that snapshot's sealed map. This is the
 * complete authorization boundary for short indices: callers must never turn
 * an unknown @e: value into a label or legacy-ref lookup.
 */
export function compactV2LegacyRefForHandle(
  handles: ReadonlyMap<string, string>,
  generation: number,
  target: string,
): string | null {
  const match = COMPACT_V2_HANDLE_RE.exec(target);
  if (match === null) return null;
  const generationRaw = match[1]!.toLowerCase();
  const indexRaw = match[2]!.toLowerCase();
  const parsedGeneration = Number.parseInt(generationRaw, 36);
  const parsedIndex = Number.parseInt(indexRaw, 36);
  if (
    !Number.isSafeInteger(parsedGeneration) ||
    !Number.isSafeInteger(parsedIndex) ||
    parsedIndex < 1 ||
    parsedGeneration !== generation ||
    parsedGeneration.toString(36) !== generationRaw ||
    parsedIndex.toString(36) !== indexRaw
  ) {
    return null;
  }
  return handles.get(target) ?? null;
}

type WireControlV2 = [string, string, string?];

// The protocol is intentionally positional to keep repeated observes small.
// Tuple schema: [ref, role(b/l/t/s/c/r/tb/m/f), optional compact description].
// The description starts with the short safe label and appends only present
// code-owned facts (`s=`, `a=`, `f=`, `q=`, `x=`). It is deliberately one
// sparse string rather than nullable columns: checked/unchecked, disabled,
// action, field, card choice, and frame context remain distinguishable without
// paying for empty slots on every row.
function wireControl(row: SafeControlV2): WireControlV2 {
  const role: Record<SafeRoleV2, string> = {
    button: "b",
    link: "l",
    textbox: "t",
    select: "s",
    checkbox: "c",
    radio: "r",
    tab: "tb",
    menuitem: "m",
    file: "f",
  };
  const wireName =
    row.name === undefined
      ? undefined
      : row.name.includes("|") || /^[nsafqx]=/.test(row.name)
        ? `n=${row.name.replace(/%/g, "%25").replace(/\|/g, "%7C")}`
        : row.name;
  const facts = [
    wireName,
    ...(row.state === undefined ? [] : [`s=${row.state}`]),
    ...(row.action === undefined ? [] : [`a=${row.action}`]),
    ...(row.field === undefined ? [] : [`f=${row.field}`]),
    ...(row.choice === undefined ? [] : [`q=${row.choice}`]),
    ...(row.frame === "main" ? [] : [`x=${row.frame === "same_origin" ? "s" : "x"}`]),
  ].filter((value): value is string => value !== undefined);
  return facts.length === 0
    ? [row.ref, role[row.role]]
    : [row.ref, role[row.role], facts.join("|")];
}

const SAFE_DESCRIPTION_MAX_CHARS = 40;
const EMAIL_VALUE_RE = /\b[A-Z0-9._%+-]+@[A-Z0-9.-]+\.[A-Z]{2,}\b/i;
const SECRET_ASSIGNMENT_RE = /\b(?:password|passcode|token|api[_ -]?key|secret)\b\s*[:=]\s*\S{4,}/i;
const HIGH_ENTROPY_TOKEN_RE = /\b[A-Za-z0-9_-]{24,}\b/;
const CARD_SECURITY_VALUE_RE = /\b(?:cvv|cvc|security\s*code)\s*[:#-]?\s*\d{3,4}\b/i;
const SAFE_DESCRIPTION_GRAMMAR_RE = /^[\p{L}\p{N}][\p{L}\p{N}\s&'’+,.!?():=/@_|-]*$/u;
const SAFE_DESCRIPTION_WORDS = new Set([
  "a",
  "access",
  "account",
  "add",
  "address",
  "an",
  "and",
  "api",
  "back",
  "bag",
  "basket",
  "billing",
  "button",
  "cancel",
  "card",
  "cart",
  "choose",
  "checkout",
  "city",
  "close",
  "code",
  "confirm",
  "contact",
  "continue",
  "control",
  "controls",
  "copy",
  "country",
  "create",
  "customer",
  "date",
  "dense",
  "delivery",
  "details",
  "different",
  "discount",
  "dismiss",
  "done",
  "email",
  "example",
  "external",
  "first",
  "finish",
  "form",
  "gift",
  "google",
  "in",
  "item",
  "key",
  "large",
  "log",
  "login",
  "merchant",
  "name",
  "native",
  "next",
  "no",
  "now",
  "option",
  "order",
  "page",
  "password",
  "pay",
  "payment",
  "phone",
  "postal",
  "previous",
  "private",
  "proceed",
  "product",
  "promo",
  "quantity",
  "region",
  "register",
  "registration",
  "review",
  "save",
  "sample",
  "search",
  "secure",
  "select",
  "serialized",
  "shipping",
  "sign",
  "signup",
  "size",
  "storefront",
  "style",
  "submit",
  "terms",
  "thanks",
  "to",
  "token",
  "united",
  "username",
  "variant",
  "verification",
  "view",
  "with",
  "workspace",
  "your",
]);

function hasSafeDescriptionGrammar(value: string): boolean {
  if (!SAFE_DESCRIPTION_GRAMMAR_RE.test(value)) return false;
  const words = value.match(/[\p{L}\p{N}]+/gu) ?? [];
  return (
    words.length > 0 &&
    words.every((word) => SAFE_DESCRIPTION_WORDS.has(word.toLowerCase()) || /^[0-9]$/.test(word))
  );
}

function containsCredentialShape(value: string): boolean {
  if (findCredentialTokens(value).length > 0) return true;
  return value
    .split(/[\s"'`()<>\[\]{},;:=]+/)
    .filter(Boolean)
    .some((token) => looksLikeCredentialValue(token));
}

function hasPanLikeDigits(value: string): boolean {
  return value.replace(/\D/g, "").length >= 13;
}

/**
 * A positive safe-text gate for the tiny semantic layer. It receives only
 * title/heading/control-label sources (never input values or arbitrary page
 * regions), rejects credential/card-shaped content, then truncates the
 * remaining human description before it can enter a wire row or delta.
 */
export function safeDescriptionV2(value: string | null | undefined): string | undefined {
  if (typeof value !== "string") return undefined;
  const normalized = value.replace(/\s+/g, " ").trim();
  if (
    normalized.length === 0 ||
    !hasSafeDescriptionGrammar(normalized) ||
    hasPanLikeDigits(normalized) ||
    EMAIL_VALUE_RE.test(normalized) ||
    SECRET_ASSIGNMENT_RE.test(normalized) ||
    CARD_SECURITY_VALUE_RE.test(normalized) ||
    HIGH_ENTROPY_TOKEN_RE.test(normalized) ||
    findOtpCredential(normalized) !== null ||
    isStandaloneOtpCredential(normalized) ||
    containsCredentialShape(normalized)
  ) {
    return undefined;
  }
  return normalized.length <= SAFE_DESCRIPTION_MAX_CHARS
    ? normalized
    : `${normalized.slice(0, SAFE_DESCRIPTION_MAX_CHARS - 1)}…`;
}

const SAFE_AUTOCOMPLETE_TOKENS = new Set([
  "address-level1",
  "address-level2",
  "address-line1",
  "address-line2",
  "address-line3",
  "bday",
  "bday-day",
  "bday-month",
  "bday-year",
  "cc-csc",
  "cc-exp",
  "cc-exp-month",
  "cc-exp-year",
  "cc-name",
  "cc-number",
  "country",
  "country-name",
  "current-password",
  "email",
  "family-name",
  "given-name",
  "honorific-prefix",
  "honorific-suffix",
  "name",
  "new-password",
  "nickname",
  "one-time-code",
  "organization",
  "organization-title",
  "postal-code",
  "shipping",
  "street-address",
  "tel",
  "tel-area-code",
  "tel-country-code",
  "tel-extension",
  "tel-local",
  "tel-local-prefix",
  "tel-local-suffix",
  "tel-national",
  "transaction-amount",
  "transaction-currency",
  "username",
]);

function safeAutocompleteV2(value: string | null | undefined): string | null {
  if (typeof value !== "string") return null;
  const tokens = value.toLowerCase().trim().split(/\s+/).filter(Boolean);
  return tokens.length > 0 && tokens.every((token) => SAFE_AUTOCOMPLETE_TOKENS.has(token))
    ? tokens.join(" ")
    : null;
}

function safeOriginV2(value: string | null | undefined): string | null {
  if (typeof value !== "string") return null;
  try {
    const parsed = new URL(value);
    return parsed.origin === value ? value : null;
  } catch {
    return null;
  }
}

export function sealRetainedInteractiveElementsV2(
  elements: readonly InteractiveElement[],
  selectorFor: (element: InteractiveElement) => string = () => "",
): InteractiveElement[] {
  const description = (value: string | null | undefined): string | null =>
    safeDescriptionV2(value) ?? null;
  const finiteToken = (
    value: string | null | undefined,
    allowed: ReadonlySet<string>,
  ): string | null => {
    const normalized = value?.toLowerCase();
    return normalized !== undefined && allowed.has(normalized) ? normalized : null;
  };
  const tags = new Set([
    "a",
    "button",
    "details",
    "input",
    "label",
    "option",
    "select",
    "summary",
    "textarea",
  ]);
  const types = new Set([
    "button",
    "checkbox",
    "date",
    "email",
    "file",
    "hidden",
    "image",
    "month",
    "number",
    "password",
    "radio",
    "reset",
    "search",
    "submit",
    "tel",
    "text",
    "time",
    "url",
    "week",
  ]);
  const roles = new Set([
    "button",
    "checkbox",
    "combobox",
    "link",
    "listbox",
    "menuitem",
    "option",
    "radio",
    "searchbox",
    "switch",
    "tab",
    "textbox",
  ]);
  return elements.map((element) => ({
    index: element.index,
    tag: finiteToken(element.tag, tags) ?? "unknown",
    type: finiteToken(element.type, types),
    id: description(element.id),
    name: description(element.name),
    placeholder: description(element.placeholder),
    ariaLabel: description(element.ariaLabel),
    role: finiteToken(element.role, roles),
    labelText: description(element.labelText),
    visibleText: description(element.visibleText),
    selector: selectorFor(element),
    visible: element.visible === true,
    inViewport: element.inViewport === true,
    inConsentWidget: element.inConsentWidget === true,
    sealed: element.sealed === true,
    href: null,
    iconLabel: description(element.iconLabel),
    title: description(element.title),
    testId: description(element.testId),
    autocomplete: safeAutocompleteV2(element.autocomplete),
    dataRole: null,
    landmark:
      typeof element.landmark === "string" &&
      /^(?:header|main|footer|nav|aside|article|section)$/.test(element.landmark)
        ? element.landmark
        : null,
    value: null,
    checked: element.checked ?? null,
    disabled: element.disabled ?? null,
    required: element.required ?? null,
    selectOptions: null,
    selectedOptionText: null,
    interactedThisRun: element.interactedThisRun === true,
    screenPath: null,
    container: null,
    containerId:
      Number.isSafeInteger(element.containerId) && (element.containerId ?? 0) > 0
        ? element.containerId
        : null,
    formId:
      Number.isSafeInteger(element.formId) && (element.formId ?? 0) > 0 ? element.formId : null,
    topmost: element.topmost ?? null,
    occludedBy: null,
    cardRadioGroup:
      element.cardRadioGroup !== null &&
      element.cardRadioGroup !== undefined &&
      Number.isSafeInteger(element.cardRadioGroup.id) &&
      Number.isSafeInteger(element.cardRadioGroup.position) &&
      Number.isSafeInteger(element.cardRadioGroup.total)
        ? {
            id: element.cardRadioGroup.id,
            position: element.cardRadioGroup.position,
            total: element.cardRadioGroup.total,
          }
        : null,
    frameOrigin: safeOriginV2(element.frameOrigin),
    frameUrl: null,
    framePath:
      typeof element.framePath === "string" && /^\d+(?:\/\d+)*$/.test(element.framePath)
        ? element.framePath
        : null,
    frameOpaque: element.frameOpaque === true,
  }));
}

export function safePageSemanticsV2(source: ObservationSemanticSourceV2): SafePageSemanticsV2 {
  const title = safeDescriptionV2(source.title);
  const headings = source.headings
    .map(safeDescriptionV2)
    .filter((value): value is string => value !== undefined)
    .filter((value, index, all) => all.indexOf(value) === index)
    .slice(0, 1);
  return {
    ...(title === undefined ? {} : { title }),
    ...(headings.length === 0 ? {} : { headings }),
  };
}

export interface SafeObservationDeltaV2 {
  added: SafeControlV2[];
  changed: SafeControlV2[];
  removed: string[];
  stageChanged: boolean;
}

/**
 * Diff only the sealed representation.  In particular, raw changes to a
 * field value, card number, live region, or merchant copy cannot cause either
 * the raw data or a page-derived derivative to cross into the delta.
 */
export function diffSafeControlsV2(
  previous: SafeObservationBaselineV2,
  stage: SafeStageV2,
  rows: readonly SafeControlV2[],
): SafeObservationDeltaV2 {
  const current = new Map(rows.map((row) => [row.ref, row]));
  const added: SafeControlV2[] = [];
  const changed: SafeControlV2[] = [];
  for (const row of rows) {
    const before = previous.byRef.get(row.ref);
    if (before === undefined) added.push(row);
    else if (JSON.stringify(wireControl(before)) !== JSON.stringify(wireControl(row)))
      changed.push(row);
  }
  const removed = [...previous.byRef.keys()].filter((ref) => !current.has(ref));
  return { added, changed, removed, stageChanged: previous.stage !== stage };
}

/**
 * Encodes a structural V2 delta. `null` deliberately asks the caller to send
 * a paged full resync instead: a delta must never exceed the hard wire budget.
 */
export function encodeV2Delta(args: {
  sessionId: string;
  stage: SafeStageV2;
  semantics?: SafePageSemanticsV2 | undefined;
  delta: SafeObservationDeltaV2;
}): Record<string, unknown> | null {
  const payload: Record<string, unknown> = {
    format: "compact-v2",
    url: "",
    text: "",
    session_id: args.sessionId,
    delta: true,
    ...(args.semantics === undefined ? {} : { semantic: args.semantics }),
    ...(args.delta.stageChanged ? { stage: args.stage } : {}),
    // `safe_table` follows the established TS delta protocol: rows are
    // upserts, irrespective of whether their ref is new or changed. This keeps
    // existing delta consumers compatible while the @e: map itself stays V2.
    ...(args.delta.added.length + args.delta.changed.length > 0
      ? { safe_table: [...args.delta.added, ...args.delta.changed].map(wireControl) }
      : {}),
    ...(args.delta.removed.length > 0 ? { removed: args.delta.removed } : {}),
  };
  return compactV2PayloadWithinBudget(payload) ? payload : null;
}

const INTENTS: ReadonlyArray<[SafeIntentV2, RegExp]> = [
  ["add_to_cart", /add\s+(?:to\s+)?(?:cart|bag|basket)/i],
  ["view_cart", /view\s+(?:cart|bag|basket)/i],
  ["checkout", /^(?:(?:go|proceed|continue)(?:\s+to)?\s+)?(?:secure\s+)?checkout(?:\s+now)?$/i],
  ["payment", /\b(?:pay(?:ment)?|card)\b/i],
  ["signup", /sign\s*up|create\s+(?:account|workspace)|register/i],
  ["login", /log\s*in|sign\s*in|continue\s+with/i],
  ["search", /search|find/i],
  ["close", /close|dismiss|cancel|no\s+thanks/i],
  ["next", /next/i],
  ["previous", /previous|back/i],
  ["submit", /submit|save|create|send/i],
  ["continue", /continue|proceed|start|accept|allow/i],
];

const BUTTON_INPUT_TYPES = new Set(["button", "submit", "reset", "image"]);

function isButtonInput(el: InteractiveElement): boolean {
  return el.tag === "input" && BUTTON_INPUT_TYPES.has((el.type ?? "").toLowerCase());
}

function candidateTexts(el: InteractiveElement): string[] {
  return [
    el.visibleText,
    el.labelText,
    el.ariaLabel,
    el.iconLabel,
    el.title,
    el.placeholder,
    el.name,
    el.id,
    ...(isButtonInput(el) ? [el.value] : []),
  ]
    .filter((part): part is string => typeof part === "string")
    .map((part) => part.replace(/[-_]+/g, " ").replace(/\s+/g, " ").trim())
    .filter(Boolean);
}

function candidateText(el: InteractiveElement): string {
  return candidateTexts(el).join(" ");
}

function controlDescription(el: InteractiveElement): string | undefined {
  // Labels are chosen from visible/accessibility naming sources only. Native
  // button values are names; field values, `name`, and `id` stay excluded.
  return safeDescriptionV2(
    el.visibleText ??
      el.labelText ??
      el.ariaLabel ??
      el.iconLabel ??
      el.title ??
      el.placeholder ??
      (isButtonInput(el) ? el.value : undefined),
  );
}

function roleOf(el: InteractiveElement): SafeRoleV2 | null {
  const role = (el.role ?? "").toLowerCase();
  const type = (el.type ?? "").toLowerCase();
  if (type === "file") return "file";
  if (isButtonInput(el)) return "button";
  if (type === "checkbox" || role === "checkbox") return "checkbox";
  if (type === "radio" || role === "radio") return "radio";
  if (el.tag === "select" || role === "combobox" || role === "listbox") return "select";
  if (el.tag === "input" || el.tag === "textarea" || role === "textbox") return "textbox";
  if (el.tag === "a" || role === "link") return "link";
  if (role === "tab") return "tab";
  if (role === "menuitem" || role === "option") return "menuitem";
  if (
    el.tag === "button" ||
    role === "button" ||
    (el.topmost !== null && el.topmost !== undefined)
  ) {
    return "button";
  }
  return null;
}

function stateOf(el: InteractiveElement): string | undefined {
  // A compact code-owned bitset: c=checked, u=unchecked, d=disabled,
  // r=required.  It is deliberately not a page-provided string.
  let state = "";
  if (el.checked === true) state += "c";
  else if (el.checked === false) state += "u";
  if (el.disabled === true) state += "d";
  if (el.required === true) state += "r";
  return state || undefined;
}

function intentOf(el: InteractiveElement): SafeIntentV2 | undefined {
  const texts = candidateTexts(el);
  return INTENTS.find(([, expression]) => texts.some((text) => expression.test(text)))?.[0];
}

function fieldOf(el: InteractiveElement): SafeFieldV2 | undefined {
  const autocomplete = (el.autocomplete ?? "").toLowerCase();
  const autocompleteTokens = new Set(autocomplete.trim().split(/\s+/).filter(Boolean));
  const hasAutocomplete = (...tokens: string[]): boolean =>
    tokens.some((token) => autocompleteTokens.has(token));
  const type = (el.type ?? "").toLowerCase();
  const text = candidateText(el).toLowerCase();
  if (type === "password" || hasAutocomplete("current-password", "new-password")) {
    return "password";
  }
  if (type === "email" || hasAutocomplete("email") || /\be-?mail\b/.test(text)) return "email";
  if (
    type === "tel" ||
    [...autocompleteTokens].some((token) => token === "tel" || token.startsWith("tel-")) ||
    /\b(phone|mobile|telephone)\b/.test(text)
  )
    return "phone";
  if (type === "search" || /\bsearch\b/.test(text)) return "search";
  if (hasAutocomplete("username") || /\b(user ?name|handle)\b/.test(text)) return "username";
  if (/\b(card|payment|cc-)/.test(`${autocomplete} ${text}`)) return "payment";
  if (hasAutocomplete("address-level2") || /\b(city|town)\b/.test(text)) return "city";
  if (hasAutocomplete("address-level1") || /\b(state|province|region)\b/.test(text))
    return "region";
  if (hasAutocomplete("postal-code") || /\b(zip|postal)\b/.test(text)) return "postal";
  if (hasAutocomplete("country", "country-name") || /\bcountry\b/.test(text)) return "country";
  if (
    hasAutocomplete("street-address", "address-line1", "address-line2", "address-line3") ||
    /\b(address|street)\b/.test(text)
  )
    return "address";
  if (
    type === "date" ||
    [...autocompleteTokens].some((token) => token.startsWith("bday")) ||
    /\bdate\b/.test(text)
  )
    return "date";
  if (/\b(quantity|qty)\b/.test(text)) return "quantity";
  if (/\b(promo|coupon|discount)\b/.test(text)) return "promo";
  if (
    [...autocompleteTokens].some((token) => token === "name" || token.endsWith("-name")) ||
    /\b(full )?name\b/.test(text)
  )
    return "name";
  return undefined;
}

/** A code-owned page-stage enum; it never forwards the URL or page copy. */
export function safeStageV2(url: string, elements: readonly InteractiveElement[]): SafeStageV2 {
  let pathname = "";
  try {
    pathname = decodeURIComponent(new URL(url).pathname).toLowerCase();
  } catch {}
  if (
    /(?:^|\/)(?:success|complete|thank-you|thank_you|finished|done)(?:\.(?:php|html?))?(?:\/|$)/.test(
      pathname,
    )
  ) {
    return "complete";
  }
  const actionableElements = elements.filter(
    (element) => element.visible === true && element.topmost !== false,
  );
  const checkoutFields = new Set<SafeFieldV2>([
    "address",
    "city",
    "region",
    "postal",
    "country",
    "payment",
  ]);
  const hasCheckoutField = actionableElements.some((el) => {
    const role = roleOf(el);
    const field = fieldOf(el);
    return (
      (role === "textbox" || role === "select") && field !== undefined && checkoutFields.has(field)
    );
  });
  const authFields = actionableElements.filter((el) => {
    const role = roleOf(el);
    if (role !== "textbox" && role !== "select") return false;
    const field = fieldOf(el);
    return field === "email" || field === "username" || field === "password";
  });
  const hasPasswordField = authFields.some((el) => fieldOf(el) === "password");
  const hasScopedAuthForm = actionableElements.some((el) => {
    if (roleOf(el) !== "button" || (intentOf(el) !== "login" && intentOf(el) !== "signup")) {
      return false;
    }
    const ownerId = el.formId ?? el.containerId;
    const framePath = el.framePath ?? null;
    return (
      ownerId !== undefined &&
      ownerId !== null &&
      authFields.some(
        (field) =>
          (field.formId ?? field.containerId) === ownerId &&
          (field.framePath ?? null) === framePath,
      )
    );
  });
  if (hasPasswordField || hasScopedAuthForm) return "auth";
  const routeStage = checkoutStageFromUrlV2(url);
  if (routeStage !== null) return routeStage;
  const hasPaymentField = actionableElements.some((el) => {
    const role = roleOf(el);
    return (role === "textbox" || role === "select") && fieldOf(el) === "payment";
  });
  const hasCheckoutAction = actionableElements.some(
    (el) => roleOf(el) === "button" && intentOf(el) === "checkout",
  );
  if (hasPaymentField || (hasCheckoutAction && hasCheckoutField)) return "checkout";
  if (actionableElements.some((el) => intentOf(el) === "add_to_cart")) return "browse";
  if (actionableElements.some((el) => roleOf(el) === "textbox" || roleOf(el) === "select"))
    return "form";
  return "browse";
}

export function checkoutStageFromUrlV2(url: string): "cart" | "checkout" | null {
  let pathname = "";
  try {
    pathname = decodeURIComponent(new URL(url).pathname).toLowerCase();
  } catch {
    return null;
  }
  if (
    /(?:^|\/)(?:checkout|secure[-_]?checkout|payment|order[-_]?review|order\/review)(?:\.(?:php|html?))?(?:\/|$)/i.test(
      pathname,
    )
  ) {
    return "checkout";
  }
  if (
    /(?:^|\/)(?:cart|shopping[-_]?cart|view[-_]?cart|basket|bag)(?:\.(?:php|html?))?(?:\/|$)/i.test(
      pathname,
    )
  ) {
    return "cart";
  }
  return null;
}

function frameOf(el: InteractiveElement, pageOrigin: string): SafeControlV2["frame"] {
  if (el.frameOrigin === null || el.frameOrigin === undefined) return "main";
  return el.frameOrigin === pageOrigin ? "same_origin" : "cross_origin";
}

export function buildSafeControlsV2(args: {
  elements: readonly InteractiveElement[];
  legacyRefs: ReadonlyMap<InteractiveElement, string>;
  generation: number;
  pageOrigin: string;
}): { rows: SafeControlV2[]; byRef: Map<string, string> } {
  const rows: Array<{ legacy: string; row: Omit<SafeControlV2, "ref">; priority: number }> = [];
  for (const el of args.elements) {
    if (el.visible !== true || el.topmost === false) continue;
    const role = roleOf(el);
    const legacy = args.legacyRefs.get(el);
    if (role === null || legacy === undefined) continue;
    const state = stateOf(el);
    const action = intentOf(el);
    const field = fieldOf(el);
    const cardChoice = el.cardRadioGroup;
    // Native TypeScript port of browse-use's compact DOM formatting: the
    // already CDP-derived interactive inventory supplies each visible control's
    // descendant/accessibility name. This pass binds that name to its own live
    // element, so no cross-serializer tag/role fallback can swap labels.
    const name = controlDescription(el);
    const row: Omit<SafeControlV2, "ref"> = {
      role,
      visibility: el.inViewport ? "viewport" : "near",
      frame: frameOf(el, args.pageOrigin),
      ...(state === undefined ? {} : { state }),
      ...(action === undefined ? {} : { action }),
      ...(field === undefined ? {} : { field }),
      ...(name === undefined ? {} : { name }),
      ...(cardChoice === null || cardChoice === undefined
        ? {}
        : { choice: `${cardChoice.position}/${cardChoice.total}` }),
    };
    rows.push({ legacy, row, priority: (el.inViewport ? 0 : 10) + (role === "button" ? 0 : 1) });
  }
  rows.sort((a, b) => a.priority - b.priority || a.legacy.localeCompare(b.legacy));
  const byRef = new Map<string, string>();
  const safeRows = rows.map(({ legacy, row }, index) => {
    // Per-snapshot compact index. Generation binding is checked before the
    // legacy live-ref is ever resolved (see resolveSessionTarget).
    const ref = `@e:${args.generation.toString(36)}.${(index + 1).toString(36)}`;
    byRef.set(ref, legacy);
    return { ref, ...row };
  });
  return { rows: safeRows, byRef };
}

export function encodeV2Page(args: {
  sessionId: string;
  stage: SafeStageV2;
  semantics?: SafePageSemanticsV2;
  rows: readonly SafeControlV2[];
  cursorFor: (offset: number) => string;
  offset?: number;
  unchanged?: boolean;
  startMetadata?: {
    hint?: string;
    userEmail?: string;
    hintOverflow?: { remaining: number; next_cursor: string };
  };
}): { payload: Record<string, unknown>; nextOffset: number } {
  const offset = args.offset ?? 0;
  if (args.unchanged === true && offset === 0) {
    const payload: Record<string, unknown> = {
      format: "compact-v2",
      url: "",
      text: "",
      session_id: args.sessionId,
      stage: args.stage,
      ...(args.startMetadata?.hint === undefined ? {} : { hint: args.startMetadata.hint }),
      ...(args.startMetadata?.userEmail === undefined
        ? {}
        : { user_email: args.startMetadata.userEmail }),
      ...(args.startMetadata?.hintOverflow === undefined
        ? {}
        : { hint_overflow: args.startMetadata.hintOverflow }),
      ...(args.semantics === undefined || Object.keys(args.semantics).length === 0
        ? {}
        : { semantic: args.semantics }),
      delta: true,
    };
    if (!compactV2PayloadWithinBudget(payload)) {
      throw new Error("compact-v2 budget metadata exceeded");
    }
    return {
      payload,
      nextOffset: 0,
    };
  }
  const visible: WireControlV2[] = [];
  // Initial observations stay decisively small. Overflow is retrieved through
  // the in-MCP query cursor, never a shell-readable snapshot file.
  const pageEnd =
    offset === 0 ? Math.min(args.rows.length, FIRST_PAGE_ROW_LIMIT) : args.rows.length;
  for (let index = offset; index < pageEnd; index += 1) {
    const candidate = args.rows[index]!;
    const remainder = args.rows.length - (index + 1);
    const payload: Record<string, unknown> = {
      format: "compact-v2",
      url: "",
      text: "",
      session_id: args.sessionId,
      stage: args.stage,
      ...(args.startMetadata?.hint === undefined ? {} : { hint: args.startMetadata.hint }),
      ...(args.startMetadata?.userEmail === undefined
        ? {}
        : { user_email: args.startMetadata.userEmail }),
      ...(args.startMetadata?.hintOverflow === undefined
        ? {}
        : { hint_overflow: args.startMetadata.hintOverflow }),
      ...(args.semantics === undefined || Object.keys(args.semantics).length === 0
        ? {}
        : { semantic: args.semantics }),
      safe_table: [...visible, wireControl(candidate)],
      ...(remainder > 0
        ? { overflow: { remaining: remainder, next_cursor: args.cursorFor(index + 1) } }
        : {}),
    };
    if (!compactV2PayloadWithinBudget(payload)) break;
    visible.push(wireControl(candidate));
  }
  const nextOffset = offset + visible.length;
  const remaining = args.rows.length - nextOffset;
  const payload: Record<string, unknown> = {
    format: "compact-v2",
    url: "",
    text: "",
    session_id: args.sessionId,
    stage: args.stage,
    ...(args.startMetadata?.hint === undefined ? {} : { hint: args.startMetadata.hint }),
    ...(args.startMetadata?.userEmail === undefined
      ? {}
      : { user_email: args.startMetadata.userEmail }),
    ...(args.startMetadata?.hintOverflow === undefined
      ? {}
      : { hint_overflow: args.startMetadata.hintOverflow }),
    ...(args.semantics === undefined || Object.keys(args.semantics).length === 0
      ? {}
      : { semantic: args.semantics }),
    safe_table: visible,
    ...(remaining > 0 ? { overflow: { remaining, next_cursor: args.cursorFor(nextOffset) } } : {}),
  };
  // The fixed fields are deliberately tiny, so failure means a hostilely long
  // session id/cursor. Fail closed rather than exceeding the wire contract.
  if (!compactV2PayloadWithinBudget(payload)) {
    throw new Error("compact-v2 budget metadata exceeded");
  }
  return { payload, nextOffset };
}
