import { createHmac } from "node:crypto";
import { Buffer } from "node:buffer";
import type { InteractiveElement } from "./browser.js";

export const OBSERVE_V2_MAX_WIRE_BYTES = 4_096;
export const OBSERVE_V2_MAX_TOKENS = 1_024;
const FIRST_PAGE_ROW_LIMIT = 4;

export type SafeRoleV2 =
  | "button"
  | "link"
  | "textbox"
  | "select"
  | "checkbox"
  | "radio"
  | "tab"
  | "menuitem"
  | "file";
export type SafeIntentV2 =
  | "search"
  | "close"
  | "next"
  | "previous"
  | "submit"
  | "continue"
  | "login"
  | "signup"
  | "add_to_cart"
  | "checkout"
  | "payment";
// These are semantic classes generated by TS, never page-provided labels. They
// make a small action map useful for forms while keeping values, merchant copy,
// live regions, and secrets on the private side of the seal.
export type SafeFieldV2 =
  | "email"
  | "password"
  | "username"
  | "name"
  | "phone"
  | "search"
  | "address"
  | "city"
  | "region"
  | "postal"
  | "country"
  | "date"
  | "quantity"
  | "promo"
  | "payment";
export type SafeStageV2 = "browse" | "auth" | "form" | "cart" | "checkout" | "complete";

export interface SafeControlV2 {
  ref: string;
  role: SafeRoleV2;
  state?: string;
  visibility: "viewport" | "near";
  action?: SafeIntentV2;
  field?: SafeFieldV2;
  /** Short, screened descriptive control label; never a field value. */
  name?: string;
  choice?: string;
  frame: "main" | "same_origin" | "cross_origin";
}

/** Raw DOM input is accepted only from title and visible heading elements. */
export interface ObservationSemanticSourceV2 {
  title: string;
  headings: readonly string[];
}

export interface SafePageSemanticsV2 {
  title?: string;
  headings?: string[];
}

export interface BrowserUseSelectedNode {
  backend_node_id: number;
  tag: string;
  role: string | null;
  /** Process-internal only. Never copy this into a safe row or a log. */
  name: string;
}

export interface SafeObservationIndexV2 {
  generation: number;
  stage: SafeStageV2;
  semantics: SafePageSemanticsV2;
  rows: SafeControlV2[];
  byRef: Map<string, string>;
  expiresAt: number;
}

/**
 * The only V2 state retained between observations.  These rows have already
 * crossed the allowlist seal: they contain HMAC refs and code-owned enums,
 * never browser-use names, DOM values, or page copy.
 */
export interface SafeObservationBaselineV2 {
  stage: SafeStageV2;
  semantics: SafePageSemanticsV2;
  byRef: Map<string, SafeControlV2>;
}

/**
 * Semantic essentials are sticky across V2 deltas. A repeat observation only
 * needs to carry them when their already-sealed representation changed; the
 * consumer retains the prior title/heading just like it retains safe_table.
 */
export function equalSafePageSemanticsV2(
  left: SafePageSemanticsV2,
  right: SafePageSemanticsV2,
): boolean {
  return left.title === right.title && (left.headings?.[0] ?? "") === (right.headings?.[0] ?? "");
}

type WireControlV2 = [string, string, string | null, string | null, string?, string?];

// These codes are protocol literals, not page text. Keeping this mapping here
// (rather than deriving it from a label) makes the short wire representation
// deterministic and preserves the closed allowlist boundary.
const WIRE_INTENT: Record<SafeIntentV2, string> = {
  search: "q",
  close: "x",
  next: "n",
  previous: "p",
  submit: "u",
  continue: "c",
  login: "i",
  signup: "g",
  add_to_cart: "a",
  checkout: "k",
  payment: "y",
};

const WIRE_FIELD: Record<SafeFieldV2, string> = {
  email: "e",
  password: "p",
  username: "u",
  name: "n",
  phone: "h",
  search: "q",
  address: "a",
  city: "c",
  region: "r",
  postal: "z",
  country: "o",
  date: "d",
  quantity: "t",
  promo: "m",
  payment: "y",
};

// The protocol is intentionally positional to keep repeated observes small.
// Tuple schema: [ref, role(b/l/t/s/c/r/tb/m/f), action|null, field|null,
// optional state/choice]. Every value is either a sealed HMAC ref or a
// code-owned finite token.
function wireControl(row: SafeControlV2): WireControlV2 {
  const role: Record<SafeRoleV2, string> = {
    button: "b",
    link: "l",
    textbox: "t",
    select: "s",
    checkbox: "c",
    radio: "r",
    tab: "tb",
    menuitem: "m",
    file: "f",
  };
  const signal = row.choice ?? row.state;
  if (row.name === undefined) {
    return signal === undefined
      ? [row.ref, role[row.role], row.action === undefined ? null : WIRE_INTENT[row.action], row.field === undefined ? null : WIRE_FIELD[row.field]]
      : [row.ref, role[row.role], row.action === undefined ? null : WIRE_INTENT[row.action], row.field === undefined ? null : WIRE_FIELD[row.field], signal];
  }
  return [
    row.ref,
    role[row.role],
    row.action === undefined ? null : WIRE_INTENT[row.action],
    row.field === undefined ? null : WIRE_FIELD[row.field],
    signal ?? "",
    row.name,
  ];
}

const SAFE_DESCRIPTION_MAX_CHARS = 40;
const EMAIL_VALUE_RE = /\b[A-Z0-9._%+-]+@[A-Z0-9.-]+\.[A-Z]{2,}\b/i;
const SECRET_ASSIGNMENT_RE = /\b(?:password|passcode|token|api[_ -]?key|secret)\b\s*[:=]\s*\S{4,}/i;
const HIGH_ENTROPY_TOKEN_RE = /\b[A-Za-z0-9_-]{24,}\b/;

function hasPanLikeDigits(value: string): boolean {
  return value.replace(/\D/g, "").length >= 13;
}

/**
 * A positive safe-text gate for the tiny semantic layer. It receives only
 * title/heading/control-label sources (never input values or arbitrary page
 * regions), rejects credential/card-shaped content, then truncates the
 * remaining human description before it can enter a wire row or delta.
 */
export function safeDescriptionV2(value: string | null | undefined): string | undefined {
  if (typeof value !== "string") return undefined;
  const normalized = value.replace(/\s+/g, " ").trim();
  if (
    normalized.length === 0 ||
    hasPanLikeDigits(normalized) ||
    EMAIL_VALUE_RE.test(normalized) ||
    SECRET_ASSIGNMENT_RE.test(normalized) ||
    HIGH_ENTROPY_TOKEN_RE.test(normalized)
  ) {
    return undefined;
  }
  return normalized.length <= SAFE_DESCRIPTION_MAX_CHARS
    ? normalized
    : `${normalized.slice(0, SAFE_DESCRIPTION_MAX_CHARS - 1)}…`;
}

export function safePageSemanticsV2(source: ObservationSemanticSourceV2): SafePageSemanticsV2 {
  const title = safeDescriptionV2(source.title);
  const headings = source.headings
    .map(safeDescriptionV2)
    .filter((value): value is string => value !== undefined)
    .filter((value, index, all) => all.indexOf(value) === index)
    .slice(0, 1);
  return {
    ...(title === undefined ? {} : { title }),
    ...(headings.length === 0 ? {} : { headings }),
  };
}

export interface SafeObservationDeltaV2 {
  added: SafeControlV2[];
  changed: SafeControlV2[];
  removed: string[];
  stageChanged: boolean;
}

/**
 * Diff only the sealed representation.  In particular, raw changes to a
 * field value, card number, live region, or merchant copy cannot cause either
 * the raw data or a page-derived derivative to cross into the delta.
 */
export function diffSafeControlsV2(
  previous: SafeObservationBaselineV2,
  stage: SafeStageV2,
  rows: readonly SafeControlV2[],
): SafeObservationDeltaV2 {
  const current = new Map(rows.map((row) => [row.ref, row]));
  const added: SafeControlV2[] = [];
  const changed: SafeControlV2[] = [];
  for (const row of rows) {
    const before = previous.byRef.get(row.ref);
    if (before === undefined) added.push(row);
    else if (JSON.stringify(wireControl(before)) !== JSON.stringify(wireControl(row))) changed.push(row);
  }
  const removed = [...previous.byRef.keys()].filter((ref) => !current.has(ref));
  return { added, changed, removed, stageChanged: previous.stage !== stage };
}

/**
 * Encodes a structural V2 delta. `null` deliberately asks the caller to send
 * a paged full resync instead: a delta must never exceed the hard wire budget.
 */
export function encodeV2Delta(args: {
  stage: SafeStageV2;
  semantics?: SafePageSemanticsV2 | undefined;
  delta: SafeObservationDeltaV2;
}): Record<string, unknown> | null {
  const payload: Record<string, unknown> = {
    format: "compact-v2",
    delta: true,
    ...(args.semantics === undefined || Object.keys(args.semantics).length === 0
      ? {}
      : { semantic: args.semantics }),
    ...(args.delta.stageChanged ? { stage: args.stage } : {}),
    // `safe_table` follows the established TS delta protocol: rows are
    // upserts, irrespective of whether their ref is new or changed. This keeps
    // existing delta consumers compatible while the @e: map itself stays V2.
    ...(args.delta.added.length + args.delta.changed.length > 0
      ? { safe_table: [...args.delta.added, ...args.delta.changed].map(wireControl) }
      : {}),
    ...(args.delta.removed.length > 0 ? { removed: args.delta.removed } : {}),
  };
  return Buffer.byteLength(JSON.stringify(payload), "utf8") <= OBSERVE_V2_MAX_WIRE_BYTES ? payload : null;
}

const INTENTS: ReadonlyArray<[SafeIntentV2, RegExp]> = [
  ["add_to_cart", /add\s+(?:to\s+)?(?:cart|bag|basket)/i],
  ["checkout", /checkout|view\s+(?:cart|bag|basket)/i],
  ["payment", /pay(?:ment)?|card/i],
  ["signup", /sign\s*up|create\s+(?:account|workspace)|register/i],
  ["login", /log\s*in|sign\s*in|continue\s+with/i],
  ["search", /search|find/i],
  ["close", /close|dismiss|cancel|no\s+thanks/i],
  ["next", /next/i],
  ["previous", /previous|back/i],
  ["submit", /submit|save|create|send/i],
  ["continue", /continue|proceed|start|accept|allow/i],
];

function candidateText(el: InteractiveElement): string {
  return [
    el.visibleText,
    el.labelText,
    el.ariaLabel,
    el.iconLabel,
    el.title,
    el.placeholder,
    el.name,
    el.id,
  ]
    .filter((part): part is string => typeof part === "string")
    .join(" ");
}

function controlDescription(el: InteractiveElement): string | undefined {
  // Labels are chosen from visible/accessibility naming sources only. `value`,
  // `name`, and `id` deliberately remain outside this allowlist.
  return safeDescriptionV2(el.visibleText ?? el.labelText ?? el.ariaLabel ?? el.iconLabel ?? el.title ?? el.placeholder);
}

function roleOf(el: InteractiveElement): SafeRoleV2 | null {
  const role = (el.role ?? "").toLowerCase();
  const type = (el.type ?? "").toLowerCase();
  if (type === "file") return "file";
  if (type === "checkbox" || role === "checkbox") return "checkbox";
  if (type === "radio" || role === "radio") return "radio";
  if (el.tag === "select" || role === "combobox" || role === "listbox") return "select";
  if (el.tag === "input" || el.tag === "textarea" || role === "textbox") return "textbox";
  if (el.tag === "a" || role === "link") return "link";
  if (role === "tab") return "tab";
  if (role === "menuitem" || role === "option") return "menuitem";
  if (el.tag === "button" || role === "button" || (el.topmost !== null && el.topmost !== undefined)) {
    return "button";
  }
  return null;
}

function stateOf(el: InteractiveElement): string | undefined {
  // A compact code-owned bitset: c=checked, u=unchecked, d=disabled-ish,
  // r=required.  It is deliberately not a page-provided string.
  let state = "";
  if (el.checked === true) state += "c";
  else if (el.checked === false) state += "u";
  if (el.sealed === true) state += "d";
  return state || undefined;
}

function intentOf(el: InteractiveElement): SafeIntentV2 | undefined {
  const text = candidateText(el);
  return INTENTS.find(([, expression]) => expression.test(text))?.[0];
}

function fieldOf(el: InteractiveElement): SafeFieldV2 | undefined {
  const autocomplete = (el.autocomplete ?? "").toLowerCase();
  const type = (el.type ?? "").toLowerCase();
  const text = candidateText(el).toLowerCase();
  if (type === "password" || autocomplete === "current-password" || autocomplete === "new-password") {
    return "password";
  }
  if (type === "email" || autocomplete === "email" || /\be-?mail\b/.test(text)) return "email";
  if (type === "tel" || autocomplete === "tel" || /\b(phone|mobile|telephone)\b/.test(text)) return "phone";
  if (type === "search" || /\bsearch\b/.test(text)) return "search";
  if (autocomplete === "username" || /\b(user ?name|handle)\b/.test(text)) return "username";
  if (/\b(card|payment|cc-)/.test(`${autocomplete} ${text}`)) return "payment";
  if (autocomplete.includes("address") || /\b(address|street)\b/.test(text)) return "address";
  if (autocomplete === "address-level2" || /\b(city|town)\b/.test(text)) return "city";
  if (autocomplete === "address-level1" || /\b(state|province|region)\b/.test(text)) return "region";
  if (autocomplete === "postal-code" || /\b(zip|postal)\b/.test(text)) return "postal";
  if (autocomplete === "country" || /\bcountry\b/.test(text)) return "country";
  if (type === "date" || autocomplete.includes("bday") || /\bdate\b/.test(text)) return "date";
  if (/\b(quantity|qty)\b/.test(text) || type === "number") return "quantity";
  if (/\b(promo|coupon|discount)\b/.test(text)) return "promo";
  if (autocomplete.includes("name") || /\b(full )?name\b/.test(text)) return "name";
  return undefined;
}

/** A code-owned page-stage enum; it never forwards the URL or page copy. */
export function safeStageV2(url: string, elements: readonly InteractiveElement[]): SafeStageV2 {
  const internalUrl = url.toLowerCase();
  if (/(?:success|complete|confirm|thank-you|thank_you|finished|done)(?:[/?#-]|$)/.test(internalUrl)) {
    return "complete";
  }
  if (elements.some((el) => intentOf(el) === "payment" || intentOf(el) === "checkout")) return "checkout";
  if (elements.some((el) => intentOf(el) === "add_to_cart")) return "browse";
  if (elements.some((el) => intentOf(el) === "login" || intentOf(el) === "signup")) return "auth";
  if (elements.some((el) => roleOf(el) === "textbox" || roleOf(el) === "select")) return "form";
  if (/(?:cart|basket|bag)(?:[/?#-]|$)/.test(internalUrl)) return "cart";
  return "browse";
}

function frameOf(el: InteractiveElement, pageOrigin: string): SafeControlV2["frame"] {
  if (el.frameOrigin === null || el.frameOrigin === undefined) return "main";
  return el.frameOrigin === pageOrigin ? "same_origin" : "cross_origin";
}

function upstreamSelected(el: InteractiveElement, selected: readonly BrowserUseSelectedNode[]): boolean {
  const tag = el.tag.toLowerCase();
  const role = (el.role ?? "").toLowerCase();
  return selected.some((node) => {
    if (node.tag.toLowerCase() !== tag) return false;
    if (role.length > 0 && node.role !== null && node.role.toLowerCase() !== role) return false;
    // Browser-use owns the selection. Its backend node ids are not available
    // in TS's action inventory, so matching is structural; raw names are never
    // copied, compared, logged, or retained on this side of the seal.
    return true;
  });
}

export function safeV2Ref(secret: Buffer, legacyRef: string): string {
  return `@e:${createHmac("sha256", secret).update(legacyRef).digest("base64url").slice(0, 12)}`;
}

export function buildSafeControlsV2(args: {
  elements: readonly InteractiveElement[];
  legacyRefs: ReadonlyMap<InteractiveElement, string>;
  secret: Buffer;
  pageOrigin: string;
  selected: readonly BrowserUseSelectedNode[];
  /** Safe refs selected by browser-use on the preceding observation. */
  previouslySelected?: ReadonlySet<string>;
}): { rows: SafeControlV2[]; byRef: Map<string, string> } {
  const rows: Array<{ row: SafeControlV2; priority: number }> = [];
  const byRef = new Map<string, string>();
  for (const el of args.elements) {
    if (el.visible !== true || el.topmost === false) continue;
    const role = roleOf(el);
    const legacy = args.legacyRefs.get(el);
    if (role === null || legacy === undefined) continue;
    const ref = safeV2Ref(args.secret, legacy);
    // Browser-use is authoritative for a NEW candidate. Once it has selected a
    // candidate, retain only its sealed HMAC ref through this page's delta
    // stream. Browser-use's serializer can legitimately vary its viewport
    // shortlist between identical snapshots; without this tiny safe cache that
    // variation looks like DOM churn and defeats the delta protocol.
    if (!upstreamSelected(el, args.selected) && !args.previouslySelected?.has(ref)) continue;
    byRef.set(ref, legacy);
    const state = stateOf(el);
    const action = intentOf(el);
    const field = fieldOf(el);
    const cardChoice = el.cardRadioGroup;
    const name = controlDescription(el);
    const row: SafeControlV2 = {
      ref,
      role,
      visibility: el.inViewport ? "viewport" : "near",
      frame: frameOf(el, args.pageOrigin),
      ...(state === undefined ? {} : { state }),
      ...(action === undefined ? {} : { action }),
      ...(field === undefined ? {} : { field }),
      ...(name === undefined ? {} : { name }),
      ...(cardChoice === null || cardChoice === undefined
        ? {}
        : { choice: `${cardChoice.position}/${cardChoice.total}` }),
    };
    rows.push({ row, priority: (el.inViewport ? 0 : 10) + (role === "button" ? 0 : 1) });
  }
  rows.sort((a, b) => a.priority - b.priority || a.row.ref.localeCompare(b.row.ref));
  return { rows: rows.map(({ row }) => row), byRef };
}

export function encodeV2Page(args: {
  sessionId: string;
  stage: SafeStageV2;
  semantics?: SafePageSemanticsV2;
  rows: readonly SafeControlV2[];
  cursorFor: (offset: number) => string;
  offset?: number;
  unchanged?: boolean;
}): { payload: Record<string, unknown>; nextOffset: number } {
  const offset = args.offset ?? 0;
  if (args.unchanged === true && offset === 0) {
    return {
      payload: {
        format: "compact-v2",
        // This is the mandatory MCP continuation handle. Unlike page data it
        // cannot be abbreviated without breaking operate_observe/act/finish.
        session_id: args.sessionId,
        stage: args.stage,
        ...(args.semantics === undefined || Object.keys(args.semantics).length === 0
          ? {}
          : { semantic: args.semantics }),
        delta: true,
      },
      nextOffset: 0,
    };
  }
  const visible: WireControlV2[] = [];
  // Initial observations stay decisively small. Overflow is retrieved through
  // the in-MCP query cursor, never a shell-readable snapshot file.
  const pageEnd = offset === 0 ? Math.min(args.rows.length, FIRST_PAGE_ROW_LIMIT) : args.rows.length;
  for (let index = offset; index < pageEnd; index += 1) {
    const candidate = args.rows[index]!;
    const remainder = args.rows.length - (index + 1);
    const payload: Record<string, unknown> = {
      format: "compact-v2",
      session_id: args.sessionId,
      stage: args.stage,
      ...(args.semantics === undefined || Object.keys(args.semantics).length === 0
        ? {}
        : { semantic: args.semantics }),
      safe_table: [...visible, wireControl(candidate)],
      ...(remainder > 0 ? { overflow: { remaining: remainder, next_cursor: args.cursorFor(index + 1) } } : {}),
    };
    if (Buffer.byteLength(JSON.stringify(payload), "utf8") > OBSERVE_V2_MAX_WIRE_BYTES) break;
    visible.push(wireControl(candidate));
  }
  const nextOffset = offset + visible.length;
  const remaining = args.rows.length - nextOffset;
  const payload: Record<string, unknown> = {
    format: "compact-v2",
    session_id: args.sessionId,
    stage: args.stage,
    ...(args.semantics === undefined || Object.keys(args.semantics).length === 0
      ? {}
      : { semantic: args.semantics }),
    safe_table: visible,
    ...(remaining > 0 ? { overflow: { remaining, next_cursor: args.cursorFor(nextOffset) } } : {}),
  };
  // The fixed fields are deliberately tiny, so failure means a hostilely long
  // session id/cursor. Fail closed rather than exceeding the wire contract.
  if (Buffer.byteLength(JSON.stringify(payload), "utf8") > OBSERVE_V2_MAX_WIRE_BYTES) {
    throw new Error("compact-v2 budget metadata exceeded");
  }
  return { payload, nextOffset };
}
